#!/usr/bin/env bash

ctr=$(buildah from docker.io/library/ubuntu:rolling)
buildah add "$ctr" entrypoint.sh /
buildah config --cmd '["lemonade-server-dev"]' "$ctr"
buildah config --entrypoint '["/entrypoint.sh"]' "$ctr"
buildah config --port 8000 "$ctr"
buildah run "$ctr" /bin/sh -c 'ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime; \
     apt update; \
     apt install -y \
     git \
     pciutils \
     mesa-vulkan-drivers \
     python3 \
     python3-pip \
     python3-venv \
     python3-invoke \
     python3-yaml \
     python3-typeguard \
     python3-packaging \
     python3-numpy \
     python3-fasteners \
     python3-git \
     python3-watchfiles \
     python3-websockets \
     python3-cpuinfo \
     python3-pytz \
     python3-zstandard \
     python3-fastapi \
     python3-uvicorn \
     python3-jinja2 \
     python3-tabulate \
     python3-sentencepiece \
     python3-dotenv \
     python3-filelock \
     python3-fsspec \
     python3-requests \
     python3-tqdm \
     python3-distro \
     python3-httpx \
     python3-regex \
     python3-protobuf \
     python3-certifi \
     python3-httpcore \
     python3-h11 \
     python3-charset-normalizer \
     python3-urllib3; \
     python3 -m venv --system-site-packages /opt/venv; \
     . /opt/venv/bin/activate; \
     mkdir -p /root/lemonade; \
     git clone https://github.com/lemonade-sdk/lemonade.git /root/lemonade/src; \
     cd /root/lemonade/src; \
     git checkout v8.1.3; \
     pip3 install ./; \
     apt autoremove --purge -y git python3-pip python3-venv; \
     apt-get clean; \
     apt-get distclean; \
     rm -rf /root/*; \
     chmod 755 /entrypoint.sh; \
     mkdir /srv/lemonade'

buildah config -v "/srv/lemonade" "$ctr"
buildah commit "$ctr" lemonade-ai
