name: 'Build Linux .deb Package'
description: 'Build Lemonade .deb package for Linux (minimal or full with Electron)'
inputs:
  include-electron:
    description: 'Whether to include the Electron app (full build)'
    required: false
    default: 'false'
outputs:
  package-name:
    description: 'The name of the generated .deb package file'
    value: ${{ steps.build-deb.outputs.package_name }}
runs:
  using: "composite"
  steps:
    - name: Install build dependencies
      shell: bash
      run: |
        set -e

        echo "Updating package lists..."
        sudo apt-get update

        echo "Installing build dependencies..."
        sudo apt-get install -y \
          build-essential \
          cmake \
          ninja-build \
          pkg-config \
          libcurl4-openssl-dev \
          libssl-dev \
          zlib1g-dev \
          git

        echo "Verifying installations..."
        cmake --version
        ninja --version
        gcc --version
        pkg-config --version

        echo "Build dependencies installed successfully!"

    - name: Setup Node.js
      if: inputs.include-electron == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Build Electron App for Linux
      if: inputs.include-electron == 'true'
      shell: bash
      run: |
        set -e

        echo "Building Electron app for Linux..."

        cd src/app

        # Install dependencies
        echo "Installing npm dependencies..."
        npm install

        # Build the Electron app for Linux
        echo "Building Electron app for Linux..."
        npm run build:linux

        # List what was created
        echo "Contents of dist-app:"
        ls -la dist-app/ || echo "dist-app directory not found"

        echo "Contents of linux-unpacked:"
        ls -la dist-app/linux-unpacked/ || echo "linux-unpacked directory not found"

        # Verify the build output exists (check both uppercase and lowercase)
        if [ -f "dist-app/linux-unpacked/lemonade" ]; then
            echo "Found: dist-app/linux-unpacked/lemonade"
        elif [ -f "dist-app/linux-unpacked/Lemonade" ]; then
            echo "Found: dist-app/linux-unpacked/Lemonade"
        else
            echo "ERROR: Electron app executable not found!"
            echo "Looking for 'lemonade' or 'Lemonade' in dist-app/linux-unpacked/"
            exit 1
        fi

        echo "Electron app build successful!"

    - name: Build C++ Server with CMake
      shell: bash
      run: |
        set -e

        echo "Building lemonade-router and lemonade-server for Linux..."

        # Create build directory
        if [ -d "build" ]; then
            echo "Removing existing build directory..."
            rm -rf build
        fi

        # Configure with preset
        echo "Configuring CMake..."
        if [ "${{ inputs.include-electron }}" == "true" ]; then
            cmake --preset default -DINCLUDE_ELECTRON_APP=ON
        else
            cmake --preset default
        fi

        # Build
        echo "Building binaries..."
        cmake --build --preset default

        # Verify binaries exist
        if [ ! -f "build/lemonade-router" ]; then
            echo "ERROR: lemonade-router not found!"
            echo "Build directory contents:"
            ls -lh build/
            exit 1
        fi

        if [ ! -f "build/lemonade-server" ]; then
            echo "ERROR: lemonade-server not found!"
            echo "Build directory contents:"
            ls -lh build/
            exit 1
        fi

        echo "✓ Binaries found successfully"

        echo "Verifying binary executability..."
        ./build/lemonade-router --version
        ./build/lemonade-server --version

        echo "C++ build successful!"

    - name: Build .deb package
      id: build-deb
      shell: bash
      run: |
        set -e

        cd build

        echo "Creating .deb package with CPack..."
        cpack -G DEB -V

        # List generated files
        echo "Files in build directory:"
        ls -lh *.deb 2>/dev/null || echo "No .deb files found in current directory"

        # Determine expected package name based on build type
        if [ "${{ inputs.include-electron }}" == "true" ]; then
            DEB_FILE="lemonade_${LEMONADE_VERSION}_amd64.deb"
            PACKAGE_TYPE="full"
        else
            DEB_FILE="lemonade-server-minimal_${LEMONADE_VERSION}_amd64.deb"
            PACKAGE_TYPE="minimal"
        fi

        echo "Looking for: $DEB_FILE"

        if [ ! -f "$DEB_FILE" ]; then
            echo "ERROR: .deb package not created!"
            echo "Contents of build directory:"
            ls -lR .
            exit 1
        fi

        echo ".deb package ($PACKAGE_TYPE) created successfully!"
        ls -lh "$DEB_FILE"

        # Show package info
        echo "Package information:"
        dpkg-deb --info "$DEB_FILE"

        echo "Package contents:"
        if [ "${{ inputs.include-electron }}" == "true" ]; then
            dpkg-deb --contents "$DEB_FILE" | head -100
        else
            dpkg-deb --contents "$DEB_FILE"
        fi

        # Output the package name for subsequent steps
        echo "package_name=$DEB_FILE" >> $GITHUB_OUTPUT
