name: 'Check Vulkan/GPU (Linux)'
description: 'Check Vulkan and GPU availability on Linux for diagnostic purposes'
inputs:
  check-rocm:
    description: 'Also check for ROCm availability'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Check Vulkan and GPU availability
      shell: bash
      run: |
        echo "=== Vulkan/GPU Diagnostic Information ==="
        
        # Check if vulkaninfo is available
        if command -v vulkaninfo &> /dev/null; then
            echo "vulkaninfo found, running diagnostic..."
            vulkaninfo --summary || echo "vulkaninfo failed with exit code $?"
        else
            echo "WARNING: vulkaninfo not found on system"
            echo "Vulkan tests may fail or hang if drivers are not properly installed"
        fi
        
        # Check for Vulkan ICD files
        echo ""
        echo "=== Checking for Vulkan ICD loader files ==="
        if [ -d "/etc/vulkan/icd.d" ]; then
            echo "ICD directory exists:"
            ls -la /etc/vulkan/icd.d/ || echo "Cannot list ICD directory"
        else
            echo "WARNING: /etc/vulkan/icd.d directory not found"
        fi
        
        # Check for GPU devices
        echo ""
        echo "=== Checking for GPU devices ==="
        if command -v lspci &> /dev/null; then
            echo "VGA/Display controllers:"
            lspci | grep -i "vga\|3d\|display" || echo "No GPU devices found"
        else
            echo "lspci not available"
        fi
        
        # Check for ROCm if requested
        if [ "${{ inputs.check-rocm }}" = "true" ]; then
            echo ""
            echo "=== Checking for ROCm ==="
            if command -v rocminfo &> /dev/null; then
                echo "rocminfo found, running diagnostic..."
                rocminfo || echo "rocminfo failed with exit code $?"
            else
                echo "rocminfo not found (expected if not using ROCm)"
            fi
        fi
        
        echo ""
        echo "=== End Vulkan/GPU Diagnostic ==="

