#!/usr/bin/env python3
"""Generate Lemonade's llama.cpp GGUF architecture allowlist."""

from __future__ import annotations

import argparse
import json
import re
import urllib.request
from pathlib import Path

ARCHITECTURE_RE = re.compile(r'\{\s*LLM_ARCH_[A-Z0-9_]+,\s*"([^"]+)"\s*\}')
EXCLUDED_ARCHITECTURES = {"(unknown)", "clip"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--versions",
        default="src/cpp/resources/backend_versions.json",
    )
    parser.add_argument(
        "--output",
        default="src/cpp/include/lemon/llamacpp_architectures_generated.h",
    )
    parser.add_argument("--source", help="Read llama-arch.cpp from a local file")
    return parser.parse_args()


def render(ref: str, source: str) -> str:
    architectures = sorted(
        set(ARCHITECTURE_RE.findall(source)) - EXCLUDED_ARCHITECTURES
    )
    if not architectures:
        raise SystemExit("No architectures found in llama-arch.cpp")
    entries = "\n".join(f'    "{name}",' for name in architectures)
    return f"""// Generated by .github/scripts/update_llamacpp_architectures.py from
// ggml-org/llama.cpp {ref} src/llama-arch.cpp. Do not edit manually.
#pragma once

#include <algorithm>
#include <array>
#include <string_view>

namespace lemon {{

inline bool llamacpp_architecture_is_supported(std::string_view architecture) {{
    static constexpr std::array<std::string_view, {len(architectures)}> architectures = {{{{
{entries}
    }}}};
    return std::binary_search(architectures.begin(), architectures.end(), architecture);
}}

}}  // namespace lemon
"""


def main() -> int:
    args = parse_args()
    versions = json.loads(Path(args.versions).read_text(encoding="utf-8"))
    ref = versions["llamacpp"]["cpu"]
    if args.source:
        source = Path(args.source).read_text(encoding="utf-8")
    else:
        url = (
            "https://raw.githubusercontent.com/ggml-org/llama.cpp/"
            f"{ref}/src/llama-arch.cpp"
        )
        with urllib.request.urlopen(url) as response:
            source = response.read().decode("utf-8")
    Path(args.output).write_text(render(ref, source), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
