name: Setup RyzenAI Serve
description: Download and setup RyzenAI Serve from build artifacts for testing

inputs:
  install-path:
    description: 'The LEMONADE_INSTALL_PATH where RyzenAI Serve should be installed'
    required: true

runs:
  using: composite
  steps:
    - name: Download RyzenAI Serve artifact
      uses: actions/download-artifact@v4
      with:
        name: ryzenai-serve
        path: ryzenai-serve-files

    - name: Setup RyzenAI Serve for testing
      shell: PowerShell
      run: |
        Write-Host "Setting up ryzenai-serve from artifact..." -ForegroundColor Cyan
        
        # First, check what we downloaded
        Write-Host "`nContents of downloaded artifact:" -ForegroundColor Yellow
        Get-ChildItem "ryzenai-serve-files" -File | ForEach-Object {
            $sizeMB = [math]::Round($_.Length / 1MB, 2)
            Write-Host "  - $($_.Name) ($sizeMB MB)" -ForegroundColor Gray
        }
        
        $ryzenaiDir = Join-Path "${{ inputs.install-path }}" "bin\ryzenai-serve"
        
        # Create ryzenai-serve directory
        New-Item -ItemType Directory -Path $ryzenaiDir -Force | Out-Null
        
        # Copy all files from artifact to ryzenai-serve directory
        Write-Host "`nCopying ryzenai-serve files to: $ryzenaiDir" -ForegroundColor Gray
        Copy-Item -Path "ryzenai-serve-files\*" -Destination $ryzenaiDir -Recurse -Force
        
        # Force filesystem sync and wait
        Start-Sleep -Seconds 2
        
        # Retry logic for verification
        $ryzenaiExe = Join-Path $ryzenaiDir "ryzenai-serve.exe"
        $maxRetries = 5
        $retryCount = 0
        $found = $false
        
        while (-not $found -and $retryCount -lt $maxRetries) {
            if (Test-Path $ryzenaiExe) {
                $found = $true
                Write-Host "[OK] ryzenai-serve.exe found at: $ryzenaiExe" -ForegroundColor Green
                
                # List a few files to confirm
                $fileCount = (Get-ChildItem $ryzenaiDir -File | Measure-Object).Count
                Write-Host "[OK] Total files in ryzenai-serve directory: $fileCount" -ForegroundColor Green
            } else {
                $retryCount++
                Write-Host "Attempt ${retryCount}/${maxRetries}: ryzenai-serve.exe not found yet, waiting..." -ForegroundColor Yellow
                Start-Sleep -Seconds 1
            }
        }
        
        if (-not $found) {
            Write-Host "ERROR: ryzenai-serve.exe not found after ${maxRetries} attempts!" -ForegroundColor Red
            Write-Host "Contents of ryzenai-serve directory:" -ForegroundColor Yellow
            Get-ChildItem $ryzenaiDir | Format-Table Name, Length
            Write-Host "`nContents of source directory:" -ForegroundColor Yellow
            Get-ChildItem "ryzenai-serve-files" | Format-Table Name, Length
            exit 1
        }

