"use client";

import { Loader2, ScrollText, Sparkles } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { useLemonade } from "@/components/providers/LemonadeProvider";
import { useToast } from "@/components/providers/ToastProvider";
import { DocumentSelect } from "@/components/documents/DocumentSelect";
import { Callout, Card, Chip, EmptyState, PageHeader, SkeletonList } from "@/components/ui/Primitives";
import { getChunks, getExtraction, saveExtraction } from "@/lib/db/repo";
import type { Chunk } from "@/lib/documents/types";
import { useDocuments } from "@/lib/hooks/useDocuments";
import { isLemonadeError } from "@/lib/lemonade/errors";
import { summariseDocument } from "@/lib/extraction/summaries";
import { SUMMARY_KINDS, type SummaryKind, type SummaryMap } from "@/lib/extraction/schemas";
import { createId, formatDuration } from "@/lib/utils/cn";

const LABELS: Record<SummaryKind, { title: string; description: string }> = {
  short: { title: "Short summary", description: "Two or three sentences." },
  detailed: { title: "Detailed summary", description: "Purpose, scope, dates and actions." },
  keyPoints: { title: "Key points", description: "The 5-8 things that matter most." },
  studentFriendly: {
    title: "Student-friendly explanation",
    description: "Plain language, no jargon.",
  },
  english: { title: "English summary", description: "About 120 words in English." },
  tamil: { title: "Tamil summary", description: "About 120 words in தமிழ்." },
};

export default function SummariesPage() {
  const { client, chatModel, isReady, beginRequest } = useLemonade();
  const { documents, activeDocument, activeDocumentId, setActiveDocumentId, loading } =
    useDocuments();
  const toast = useToast();

  const [summaries, setSummaries] = useState<SummaryMap>({});
  const [chunks, setChunks] = useState<Chunk[]>([]);
  const [busyKind, setBusyKind] = useState<SummaryKind | null>(null);
  const [stage, setStage] = useState<string | null>(null);

  useEffect(() => {
    if (!activeDocumentId) return;
    let cancelled = false;
    void (async () => {
      const [record, docChunks] = await Promise.all([
        getExtraction(activeDocumentId, "summaries"),
        getChunks(activeDocumentId),
      ]);
      if (cancelled) return;
      setSummaries((record?.payload as SummaryMap | undefined) ?? {});
      setChunks(docChunks);
    })();
    return () => {
      cancelled = true;
    };
  }, [activeDocumentId]);

  const generate = useCallback(
    async (kind: SummaryKind) => {
      if (!activeDocument || !chatModel) return;
      setBusyKind(kind);
      setStage(null);
      const endRequest = beginRequest();

      try {
        const result = await summariseDocument(client, chatModel, chunks, kind, {
          onProgress: setStage,
        });

        const next: SummaryMap = {
          ...summaries,
          [kind]: {
            kind,
            text: result.text,
            model: chatModel,
            createdAt: Date.now(),
            durationMs: result.durationMs,
            hierarchical: result.hierarchical,
          },
        };
        setSummaries(next);

        await saveExtraction({
          id: createId("sum"),
          documentId: activeDocument.id,
          kind: "summaries",
          payload: next,
          model: chatModel,
          createdAt: Date.now(),
          durationMs: result.durationMs,
        });

        toast.success(`${LABELS[kind].title} generated in ${formatDuration(result.durationMs)}.`);
      } catch (error) {
        toast.error(isLemonadeError(error) ? error.displayMessage : (error as Error).message);
      } finally {
        endRequest();
        setBusyKind(null);
        setStage(null);
      }
    },
    [activeDocument, beginRequest, chatModel, chunks, client, summaries, toast],
  );

  if (loading) return <SkeletonList rows={3} />;

  if (documents.length === 0) {
    return (
      <EmptyState
        icon={<ScrollText className="h-8 w-8" aria-hidden />}
        title="No documents to summarise"
        description="Upload a notice or circular first — summaries are generated from the document you processed locally."
        action={
          <Link href="/documents" className="btn-primary">
            Go to documents
          </Link>
        }
      />
    );
  }

  const totalWords = chunks.reduce((sum, chunk) => sum + chunk.wordCount, 0);

  return (
    <>
      <PageHeader
        title="Summaries"
        description="Six views of the same document, all generated by your local Lemonade Server. Long documents are summarised in stages rather than in one oversized request."
      />

      <div className="flex flex-col gap-4">
        <Card>
          <DocumentSelect
            documents={documents}
            value={activeDocumentId}
            onChange={(id) => void setActiveDocumentId(id)}
          />
          <p className="mt-2 text-xs text-ink-muted">
            {chunks.length} chunks · {totalWords.toLocaleString()} words
            {totalWords > 2400 ? " · hierarchical summarisation will be used" : ""}
          </p>
        </Card>

        {!isReady ? (
          <Callout tone="warning" title="Finish setup first">
            Connect Lemonade and pick a chat model on the <Link href="/setup">Setup page</Link>.
          </Callout>
        ) : null}

        <div className="grid gap-4 md:grid-cols-2">
          {SUMMARY_KINDS.map((kind) => {
            const record = summaries[kind];
            const busy = busyKind === kind;
            return (
              <Card key={kind} className="flex flex-col">
                <div className="mb-2 flex items-start justify-between gap-3">
                  <div>
                    <h2 className="text-sm font-semibold text-ink">{LABELS[kind].title}</h2>
                    <p className="text-xs text-ink-muted">{LABELS[kind].description}</p>
                  </div>
                  <button
                    type="button"
                    className="btn-ghost shrink-0 text-xs"
                    disabled={!isReady || busyKind !== null || chunks.length === 0}
                    onClick={() => void generate(kind)}
                  >
                    {busy ? (
                      <Loader2 className="h-3.5 w-3.5 animate-spin" aria-hidden />
                    ) : (
                      <Sparkles className="h-3.5 w-3.5" aria-hidden />
                    )}
                    {record ? "Regenerate" : "Generate"}
                  </button>
                </div>

                {busy ? (
                  <p className="text-sm text-ink-muted">{stage ?? "Generating…"}</p>
                ) : record ? (
                  <>
                    <p className="prose-answer flex-1">{record.text}</p>
                    <p className="mt-3 flex flex-wrap items-center gap-2 text-xs text-ink-faint">
                      <Chip>{record.model}</Chip>
                      <span>{formatDuration(record.durationMs)}</span>
                      {record.hierarchical ? <Chip tone="brand">hierarchical</Chip> : null}
                    </p>
                  </>
                ) : (
                  <p className="text-sm text-ink-faint">Not generated yet.</p>
                )}
              </Card>
            );
          })}
        </div>
      </div>
    </>
  );
}
