#include <lemon/utils/aixlog.hpp>

#include "lemon/model_manager.h"
#include "lemon/model_types.h"
#include "lemon/server/api_route.h"
#include "lemon/server/gateway_conversion.h"

namespace lemon {
namespace {

using json = nlohmann::json;

json build_ollama_capabilities(const ModelInfo& info) {
    json capabilities = json::array();
    ModelType model_type = get_model_type_from_labels(info.labels);

    if (model_type == ModelType::LLM) {
        capabilities.push_back("completion");
    } else if (model_type == ModelType::EMBEDDING) {
        capabilities.push_back("embedding");
    }

    if (has_label(info.labels, "tool-calling") || has_label(info.labels, "tools")) {
        capabilities.push_back("tools");
    }

    if (has_label(info.labels, "vision")) {
        capabilities.push_back("vision");
    }

    if (has_label(info.labels, "reasoning")) {
        capabilities.push_back("thinking");
    }

    return capabilities;
}

class ShowRoute : public ApiRoute {
public:
    using ApiRoute::ApiRoute;

    RouteSpec spec() const override {
        RouteSpec s;
        s.id = "ollama.show";
        s.methods = {"POST"};
        s.paths = {"/api/show"};
        s.prefixes = Prefixes::Root;
        s.summary = "Model details";
        s.description = "Describes one registered model in Ollama's format.";
        s.notes = {
            "`capabilities` follows the model's labels: `completion` for chat models, "
            "`embedding` for embedding models, plus `tools`, `vision` and `thinking` when the "
            "model carries the matching label.",
            "An unknown model answers `404` with `model '<name>' not found`.",
        };
        s.args = {
            {"model", ArgIn::JsonBody, {{"type", "string"}}, true, Support::Available,
             "Model to describe. A `:latest` tag is ignored."},
            {"name", ArgIn::JsonBody, {{"type", "string"}}, false, Support::Available,
             "Older name for `model`; wins when both are given."},
        };

        RouteResponse response;
        response.format = ResponseFormat::Json;
        response.schema = json::parse(R"({
            "type": "object",
            "required": ["modelfile", "parameters", "template", "details", "capabilities", "model_info"],
            "properties": {
                "modelfile": {"type": "string", "description": "A FROM line naming the checkpoint."},
                "parameters": {"type": "string", "description": "num_ctx followed by the model's configured context size."},
                "template": {"type": "string", "description": "Always empty."},
                "details": {},
                "capabilities": {"type": "array", "items": {"enum": ["completion", "embedding", "tools", "vision", "thinking"]}},
                "model_info": {"type": "object", "description": "general.architecture (the recipe) and <recipe>.context_length; the other keys are always 0."}
            }
        })");
        response.schema["properties"]["details"] = ollama_details_schema();
        response.example = json::parse(R"({"model": "Qwen3-0.6B-GGUF"})");
        s.responses = {response};
        return s;
    }

    void handle(RouteRequest& req, httplib::Response& res) override {
        try {
            auto request_json = json::parse(req.http.body);

            std::string name = strip_latest_tag((!request_json.value("model", "").empty() && request_json.value("name", "").empty()) ?
            request_json.value("model", "") : request_json.value("name", ""));

            if (name.empty()) {
                res.status = 400;
                res.set_content(R"({"error":"name is required"})", "application/json");
                return;
            }

            if (!ctx_.model_manager->model_exists(name)) {
                res.status = 404;
                json error = {{"error", "model '" + name + "' not found"}};
                res.set_content(error.dump(), "application/json");
                return;
            }

            auto info = ctx_.model_manager->get_model_info(name);
            int ctx_size = info.recipe_options.get_option("ctx_size");

            json response = {
                {"modelfile", "# Modelfile generated by Lemonade\nFROM " + info.checkpoint()},
                {"parameters", "num_ctx " + std::to_string(ctx_size)},
                {"template", ""},
                {"details", ollama_details(name, info.recipe, info.checkpoint())},
                {"capabilities", build_ollama_capabilities(info)},
                {"model_info", {
                    {"general.architecture", info.recipe},
                    {info.recipe + ".context_length", ctx_size},
                    {"general.file_type", 0},
                    {"general.parameter_count", 0},
                    {"general.quantization_version", 0}
                }}
            };

            res.set_content(response.dump(), "application/json");

        } catch (const std::exception& e) {
            LOG(ERROR, "OllamaApi") << "Error in /api/show: " << e.what() << std::endl;
            res.status = 500;
            json error = {{"error", std::string(e.what())}};
            res.set_content(error.dump(), "application/json");
        }
    }
};

} // namespace

std::unique_ptr<ApiRoute> make_ollama_show_route(ServerContext& ctx) {
    return std::make_unique<ShowRoute>(ctx);
}

} // namespace lemon
