#!/usr/bin/env python3
"""Stress test for Lemonade Server."""

import argparse
import concurrent.futures
import random
import time

import requests


def send_request(url, model, max_tokens, req_id, prompt):
    payload = {
        "model": model,
        "messages": [{"role": "user", "content": prompt}],
        "max_completion_tokens": max_tokens,
    }
    start = time.time()
    try:
        r = requests.post(
            f"{url}/v1/chat/completions",
            json=payload,
            timeout=120,
        )
        elapsed = time.time() - start
        status = r.status_code
        tokens = 0
        if status == 200:
            usage = r.json().get("usage", {})
            tokens = usage.get("completion_tokens", 0)
        return (req_id, status, elapsed, tokens)
    except Exception:
        return (req_id, -1, time.time() - start, 0)


def main():
    p = argparse.ArgumentParser(
        description=(
            "Stress test for Lemonade Server. "
            "Sends concurrent chat completion "
            "requests and reports throughput."
        ),
    )
    p.add_argument(
        "--url",
        default="http://localhost:8000",
        help=("Base URL of the Lemonade Server " "(default: http://localhost:8000)"),
    )
    p.add_argument(
        "--model",
        default="Qwen3-0.6B-GGUF",
        help=("Model name to use for inference " "(default: Qwen3-0.6B-GGUF)"),
    )
    p.add_argument(
        "--requests",
        type=int,
        default=30,
        help=("Total number of requests to send " "(default: 30)"),
    )
    p.add_argument(
        "--concurrency",
        type=int,
        default=4,
        help=("Number of concurrent requests " "(default: 4)"),
    )
    p.add_argument(
        "--max-tokens",
        type=int,
        default=50,
        help=("Max completion tokens per request " "(default: 50)"),
    )
    p.add_argument(
        "--seed",
        type=int,
        default=None,
        help=("RNG seed for reproducibility " "(default: time-based)"),
    )
    args = p.parse_args()

    seed = args.seed if args.seed is not None else int(time.time() * 1000) & 0xFFFFFFFF
    rng = random.Random(seed)

    selected = [rng.choice(PROMPTS) for _ in range(args.requests)]

    print(f"Stress test: {args.requests} requests, " f"{args.concurrency} concurrent")
    print(f"Model: {args.model}")
    print(f"Max tokens: {args.max_tokens}")
    print(f"Prompt pool: {len(PROMPTS)} prompts")
    print(f"Seed: {seed}")
    print()

    results = []
    t0 = time.time()

    with concurrent.futures.ThreadPoolExecutor(max_workers=args.concurrency) as pool:
        futures = [
            pool.submit(
                send_request,
                args.url,
                args.model,
                args.max_tokens,
                i,
                selected[i],
            )
            for i in range(args.requests)
        ]
        for f in concurrent.futures.as_completed(futures):
            rid, status, elapsed, tokens = f.result()
            results.append((rid, status, elapsed, tokens))
            tps = tokens / elapsed if elapsed > 0 else 0
            print(
                f"  req {rid:3d}: "
                f"status={status} "
                f"time={elapsed:.2f}s "
                f"tokens={tokens} "
                f"tps={tps:.1f}"
            )

    wall = time.time() - t0
    ok = sum(1 for _, s, _, _ in results if s == 200)
    total_tok = sum(t for _, _, _, t in results)
    times = [e for _, s, e, _ in results if s == 200]

    print()
    print("--- Summary ---")
    print(f"Total time:   {wall:.1f}s")
    print(f"Succeeded:    {ok}/{args.requests}")
    print(f"Total tokens: {total_tok}")
    if times:
        print(f"Avg latency:  " f"{sum(times)/len(times):.2f}s")
        print(f"Min latency:  {min(times):.2f}s")
        print(f"Max latency:  {max(times):.2f}s")
    print(f"Throughput:   " f"{total_tok/wall:.1f} tok/s overall")


# ============================================================
# Prompt pool (~1010 prompts across diverse categories)
# ============================================================

PROMPTS = [
    # --- Science & Physics (100) ---
    "Explain quantum computing in simple terms.",
    "Summarize the theory of relativity.",
    "What is machine learning?",
    "How does a nuclear reactor work?",
    "What is the Heisenberg uncertainty principle?",
    "Explain the double-slit experiment.",
    "What is dark matter?",
    "How do black holes form?",
    "What is the Big Bang theory?",
    "Explain string theory briefly.",
    "What causes the Northern Lights?",
    "How does a laser work?",
    "What is superconductivity?",
    "Explain entropy in thermodynamics.",
    "What is the Doppler effect?",
    "How do magnets work?",
    "What is Schrodinger's cat?",
    "Explain the photoelectric effect.",
    "What is a neutron star?",
    "How does nuclear fusion differ from fission?",
    "What is the Higgs boson?",
    "Explain wave-particle duality.",
    "What is Hawking radiation?",
    "How does gravity work in general relativity?",
    "What is quantum entanglement?",
    "Explain the three laws of thermodynamics.",
    "What is the speed of light in a vacuum?",
    "How do transistors work?",
    "What is plasma in physics?",
    "Explain the concept of spacetime.",
    "What is antimatter?",
    "How do particle accelerators work?",
    "What is the strong nuclear force?",
    "Explain Brownian motion.",
    "What is a quasar?",
    "How does a telescope work?",
    "What is the Coriolis effect?",
    "Explain Bernoulli's principle.",
    "What is the electromagnetic spectrum?",
    "How do solar panels convert sunlight?",
    "What is quantum tunneling?",
    "Explain the concept of half-life.",
    "What is a supernova?",
    "How does radar work?",
    "What is the Casimir effect?",
    "Explain chaos theory briefly.",
    "What is Bose-Einstein condensate?",
    "How does an MRI machine work?",
    "What is the weak nuclear force?",
    "Explain the concept of escape velocity.",
    "What is cosmic microwave background?",
    "How does a gyroscope maintain balance?",
    "What is the Pauli exclusion principle?",
    "Explain superfluidity.",
    "What is Cherenkov radiation?",
    "How does a Geiger counter work?",
    "What is the Planck length?",
    "Explain the twin paradox.",
    "What is gravitational lensing?",
    "How do fiber optics transmit data?",
    "What is the Meissner effect?",
    "Explain the concept of inertia.",
    "What is a Dyson sphere?",
    "How does a mass spectrometer work?",
    "What is the Chandrasekhar limit?",
    "Explain the photoelectric threshold.",
    "What is zero-point energy?",
    "How does an electron microscope work?",
    "What is the Roche limit?",
    "Explain the concept of torque.",
    "What is a Bose gas?",
    "How does a cathode ray tube work?",
    "What is the Kelvin temperature scale?",
    "Explain the principle of least action.",
    "What is a Penrose diagram?",
    "How does a calorimeter measure heat?",
    "What is the Leidenfrost effect?",
    "Explain the concept of viscosity.",
    "What is a white dwarf star?",
    "How does acoustic levitation work?",
    "What is the Stefan-Boltzmann law?",
    "Explain the concept of buoyancy.",
    "What is a pulsar?",
    "How does ultrasound imaging work?",
    "What is the Zeeman effect?",
    "Explain the concept of resonance.",
    "What is a magnetar?",
    "How does a barometer measure pressure?",
    "What is the Lamb shift?",
    "Explain the concept of impedance.",
    "What is a Fermi gas?",
    "How does a thermometer work?",
    "What is the Hall effect?",
    "Explain the concept of capacitance.",
    "What is a red giant star?",
    "How does a seismograph work?",
    "What is the Stark effect?",
    "Explain the concept of inductance.",
    "What is cosmic inflation?",
    "How does a spectrometer work?",
    # --- Biology & Medicine (100) ---
    "How does DNA replication work?",
    "What is CRISPR gene editing?",
    "Explain how vaccines work.",
    "What is the human microbiome?",
    "How does the immune system fight viruses?",
    "What is mitosis?",
    "Explain photosynthesis.",
    "What are stem cells?",
    "How does the nervous system transmit signals?",
    "What is epigenetics?",
    "Explain how antibiotics work.",
    "What is the endocrine system?",
    "How do enzymes catalyze reactions?",
    "What is mRNA?",
    "Explain the Krebs cycle.",
    "What is apoptosis?",
    "How does the liver detoxify the body?",
    "What is the lymphatic system?",
    "Explain how muscles contract.",
    "What is a prion?",
    "How do red blood cells carry oxygen?",
    "What is the blood-brain barrier?",
    "Explain how the heart pumps blood.",
    "What is the gut-brain axis?",
    "How does the kidney filter blood?",
    "What is cellular respiration?",
    "Explain how neurons fire.",
    "What is homeostasis?",
    "How does the eye perceive color?",
    "What is the role of ribosomes?",
    "Explain how bones heal after a fracture.",
    "What is the function of the spleen?",
    "How does the ear convert sound?",
    "What is the complement system?",
    "Explain how fat cells store energy.",
    "What is the role of the hypothalamus?",
    "How does taste perception work?",
    "What is the role of telomeres?",
    "Explain how platelets form clots.",
    "What is the difference between RNA and DNA?",
    "How does the pancreas regulate glucose?",
    "What is the function of the appendix?",
    "Explain how white blood cells work.",
    "What is the role of the cerebellum?",
    "How does smell perception work?",
    "What is the function of the thymus?",
    "Explain how skin repairs itself.",
    "What is the role of myelin sheaths?",
    "How does the body regulate temperature?",
    "What is the function of the adrenal glands?",
    "Explain how the lungs exchange gases.",
    "What is a synapse?",
    "How does the body produce antibodies?",
    "What is the role of the pituitary gland?",
    "Explain how hair grows.",
    "What is the function of the gallbladder?",
    "How does the stomach digest food?",
    "What is the role of the thyroid gland?",
    "Explain how nails grow.",
    "What is the function of the tonsils?",
    "How does the intestine absorb nutrients?",
    "What is the role of the pineal gland?",
    "Explain how tears are produced.",
    "What is the function of the parathyroid?",
    "How does the body metabolize alcohol?",
    "What is the role of the vagus nerve?",
    "Explain how the cornea focuses light.",
    "What is the function of bone marrow?",
    "How does the body fight bacterial infection?",
    "What is the role of collagen?",
    "Explain how a fever helps fight illness.",
    "What is the function of synovial fluid?",
    "How does the body produce insulin?",
    "What is the role of the amygdala?",
    "Explain how vitamin D is synthesized.",
    "What is the function of the epiglottis?",
    "How does the body process cholesterol?",
    "What is the role of the hippocampus?",
    "Explain how melatonin regulates sleep.",
    "What is the function of the diaphragm?",
    "How does the body maintain pH balance?",
    "What is the role of the prefrontal cortex?",
    "Explain how the cochlea detects sound.",
    "What is the function of the retina?",
    "How does the body repair DNA damage?",
    "What is the role of the basal ganglia?",
    "Explain how proprioception works.",
    "What is the function of the uvula?",
    "How does the body absorb iron?",
    "What is the role of the thalamus?",
    "Explain how calcium strengthens bones.",
    "What is the function of the larynx?",
    "How does the body produce cortisol?",
    "What is the role of the corpus callosum?",
    "Explain how bilirubin is processed.",
    "What is the function of the esophagus?",
    "How does the body maintain electrolytes?",
    "What is the role of the medulla oblongata?",
    "Explain how wound healing works.",
    "What is the function of the periosteum?",
    "How does the body produce adrenaline?",
    "What is the role of the pons?",
    # --- Programming & Technology (100) ---
    "List 5 programming languages and uses.",
    "Explain how a CPU works.",
    "What is the difference between TCP and UDP?",
    "How does a hash table work?",
    "What is the difference between a stack and queue?",
    "Explain the concept of recursion.",
    "What is a binary search tree?",
    "How does garbage collection work?",
    "What is the difference between SQL and NoSQL?",
    "Explain the CAP theorem.",
    "What is a REST API?",
    "How does HTTPS encryption work?",
    "What is the difference between threads and processes?",
    "Explain the concept of Big O notation.",
    "What is a linked list?",
    "How does a compiler differ from interpreter?",
    "What is the difference between Git and SVN?",
    "Explain the concept of polymorphism.",
    "What is a deadlock in computing?",
    "How does a DNS server resolve domains?",
    "What is containerization?",
    "Explain the concept of microservices.",
    "What is a race condition?",
    "How does a load balancer work?",
    "What is the difference between HTTP 1 and 2?",
    "Explain the concept of middleware.",
    "What is a message queue?",
    "How does a CDN improve performance?",
    "What is the difference between SOAP and REST?",
    "Explain the concept of dependency injection.",
    "What is a graph database?",
    "How does WebSocket differ from HTTP?",
    "What is the difference between OOP and FP?",
    "Explain the concept of event-driven architecture.",
    "What is a B-tree?",
    "How does virtual memory work?",
    "What is the difference between IPv4 and IPv6?",
    "Explain the concept of sharding.",
    "What is a heap data structure?",
    "How does a blockchain work?",
    "What is the difference between SSL and TLS?",
    "Explain the concept of idempotency.",
    "What is a trie data structure?",
    "How does a reverse proxy work?",
    "What is the difference between CISC and RISC?",
    "Explain the concept of eventual consistency.",
    "What is a skip list?",
    "How does a firewall filter traffic?",
    "What is the difference between L1 and L2 cache?",
    "Explain the concept of ACID transactions.",
    "What is a Bloom filter?",
    "How does a VPN tunnel work?",
    "What is the difference between SSD and HDD?",
    "Explain the concept of map-reduce.",
    "What is a red-black tree?",
    "How does OAuth authentication work?",
    "What is the difference between mutex and semaphore?",
    "Explain the concept of CQRS.",
    "What is an AVL tree?",
    "How does a packet switch router work?",
    "What is the difference between RAID 0 and RAID 1?",
    "Explain the concept of circuit breaking.",
    "What is a Fibonacci heap?",
    "How does ARP resolve MAC addresses?",
    "What is the difference between TCP SYN and ACK?",
    "Explain the concept of back-pressure.",
    "What is a segment tree?",
    "How does BGP routing work?",
    "What is the difference between gRPC and REST?",
    "Explain the concept of service mesh.",
    "What is a disjoint set data structure?",
    "How does NAT translation work?",
    "What is the difference between monolith and microservice?",
    "Explain the concept of blue-green deployment.",
    "What is a suffix array?",
    "How does DHCP assign IP addresses?",
    "What is the difference between Docker and Kubernetes?",
    "Explain the concept of canary releases.",
    "What is a Fenwick tree?",
    "How does ICMP work?",
    "What is the difference between REST and GraphQL?",
    "Explain the concept of feature flags.",
    "What is a KD-tree?",
    "How does multicast networking work?",
    "What is a database index?",
    "Explain the concept of write-ahead logging.",
    "What is a radix tree?",
    "How does a proxy server work?",
    "What is the difference between stack and heap memory?",
    "Explain the concept of connection pooling.",
    "What is a hash map collision?",
    "How does a CPU pipeline work?",
    "What is the difference between encoding and encryption?",
    "Explain the concept of rate limiting.",
    "What is a priority queue?",
    "How does branch prediction work?",
    "What is the difference between latency and throughput?",
    "Explain the concept of data normalization.",
    "What is a circular buffer?",
    "How does out-of-order execution work?",
    "What is the difference between symmetric and asymmetric encryption?",
    "Explain the concept of materialized views.",
    # --- Mathematics (100) ---
    "What is the Pythagorean theorem?",
    "Explain the concept of prime numbers.",
    "What is calculus used for?",
    "Explain the fundamental theorem of algebra.",
    "What is a Fourier transform?",
    "What is the golden ratio?",
    "Explain Euler's identity.",
    "What is a Fibonacci sequence?",
    "How does linear algebra apply to graphics?",
    "What is the Riemann hypothesis?",
    "Explain probability vs statistics.",
    "What is Bayes' theorem?",
    "How does matrix multiplication work?",
    "What is the Central Limit Theorem?",
    "Explain the concept of a derivative.",
    "What is an integral?",
    "How do logarithms work?",
    "What is the binomial theorem?",
    "Explain the concept of a limit.",
    "What is a differential equation?",
    "How does modular arithmetic work?",
    "What is the Monte Carlo method?",
    "Explain the concept of a vector space.",
    "What is a Markov chain?",
    "How does regression analysis work?",
    "What is the dot product of two vectors?",
    "Explain the concept of eigenvalues.",
    "What is a permutation?",
    "How does the pigeonhole principle work?",
    "What is a combination?",
    "Explain the concept of a group in algebra.",
    "What is a ring in abstract algebra?",
    "How does the Euclidean algorithm work?",
    "What is a field in mathematics?",
    "Explain the concept of topology.",
    "What is a manifold?",
    "How does graph theory apply to networks?",
    "What is a Hamiltonian path?",
    "Explain the concept of a determinant.",
    "What is an Euler path?",
    "How does the simplex method work?",
    "What is a convex function?",
    "Explain the concept of a series.",
    "What is a Taylor series?",
    "How does numerical integration work?",
    "What is a Laplace transform?",
    "Explain the concept of complex numbers.",
    "What is the quadratic formula?",
    "How does Gaussian elimination work?",
    "What is a partial derivative?",
    "Explain the chain rule in calculus.",
    "What is divergence in vector calculus?",
    "How does gradient descent work?",
    "What is the Jacobian matrix?",
    "Explain the mean value theorem.",
    "What is L'Hopital's rule?",
    "How does Cramer's rule solve equations?",
    "What is the Hessian matrix?",
    "Explain the implicit function theorem.",
    "What is a Cauchy sequence?",
    "How does the Newton-Raphson method work?",
    "What is a Lebesgue integral?",
    "Explain the residue theorem.",
    "What is a Green's function?",
    "How does the method of characteristics work?",
    "What is a Lyapunov function?",
    "Explain the Gauss-Bonnet theorem.",
    "What is a Hilbert space?",
    "How does the fast Fourier transform work?",
    "What is a Banach space?",
    "Explain the Cauchy-Schwarz inequality.",
    "What is the triangle inequality?",
    "How does the power method find eigenvalues?",
    "What is singular value decomposition?",
    "Explain the spectral theorem.",
    "What is a positive definite matrix?",
    "How does the QR algorithm work?",
    "What is the Jordan normal form?",
    "Explain the Cayley-Hamilton theorem.",
    "What is a nilpotent matrix?",
    "How does Cholesky decomposition work?",
    "What is a stochastic matrix?",
    "Explain the Perron-Frobenius theorem.",
    "What is a doubly stochastic matrix?",
    "How does the LU decomposition work?",
    "What is a Toeplitz matrix?",
    "Explain the Woodbury matrix identity.",
    "What is a circulant matrix?",
    "How does the conjugate gradient method work?",
    "What is a Vandermonde matrix?",
    "Explain the Sherman-Morrison formula.",
    "What is a Hadamard matrix?",
    "How does the Lanczos algorithm work?",
    "What is the Kronecker product?",
    "Explain the matrix exponential.",
    "What is a companion matrix?",
    "How does the Arnoldi iteration work?",
    "What is a projection matrix?",
    "Explain the trace of a matrix.",
    "What is the Frobenius norm?",
    "How does the Gram-Schmidt process work?",
    # --- History (100) ---
    "What caused World War I?",
    "Who built the Great Pyramids of Giza?",
    "What was the Renaissance?",
    "Explain the Industrial Revolution.",
    "What was the Roman Empire's legacy?",
    "Who was Alexander the Great?",
    "What caused the French Revolution?",
    "Explain the Age of Exploration.",
    "What was the Silk Road?",
    "Who was Genghis Khan?",
    "What caused the fall of the Roman Empire?",
    "Explain the Enlightenment period.",
    "What was the Ottoman Empire?",
    "Who was Cleopatra?",
    "What caused the American Civil War?",
    "Explain the Magna Carta.",
    "What was the Byzantine Empire?",
    "Who was Julius Caesar?",
    "What caused the Black Death?",
    "Explain the Protestant Reformation.",
    "What was the Mongol Empire?",
    "Who was Charlemagne?",
    "What caused the Hundred Years' War?",
    "Explain the Meiji Restoration.",
    "What was the Spanish Inquisition?",
    "Who was Hannibal Barca?",
    "What caused the Russian Revolution?",
    "Explain the Treaty of Versailles.",
    "What was the Cold War about?",
    "Who was Napoleon Bonaparte?",
    "What caused the Great Depression?",
    "Explain the Marshall Plan.",
    "What was the Berlin Wall?",
    "Who was Mahatma Gandhi?",
    "What caused the Cuban Missile Crisis?",
    "Explain the Bretton Woods system.",
    "What was the Space Race?",
    "Who was Winston Churchill?",
    "What caused the Vietnam War?",
    "Explain the Truman Doctrine.",
    "What was the cultural revolution in China?",
    "Who was Martin Luther King Jr.?",
    "What caused the Korean War?",
    "Explain the Yalta Conference.",
    "What was the Iron Curtain?",
    "Who was Nelson Mandela?",
    "What caused the Suez Crisis?",
    "Explain the Munich Agreement.",
    "What was the League of Nations?",
    "Who was Otto von Bismarck?",
    "What caused the Boer Wars?",
    "Explain the Congress of Vienna.",
    "What was the Dreyfus Affair?",
    "Who was Queen Victoria?",
    "What caused the Opium Wars?",
    "Explain the Scramble for Africa.",
    "What was the Boxer Rebellion?",
    "Who was Simón Bolívar?",
    "What caused the Taiping Rebellion?",
    "Explain the Emancipation Proclamation.",
    "What was the Zulu Kingdom?",
    "Who was Tokugawa Ieyasu?",
    "What caused the Crimean War?",
    "Explain the Monroe Doctrine.",
    "What was the Haitian Revolution?",
    "Who was Catherine the Great?",
    "What caused the Seven Years' War?",
    "Explain the Declaration of Independence.",
    "What was the Louisiana Purchase?",
    "Who was Frederick the Great?",
    "What caused the War of 1812?",
    "Explain the Missouri Compromise.",
    "What was Manifest Destiny?",
    "Who was Sitting Bull?",
    "What caused the Mexican-American War?",
    "Explain the Compromise of 1850.",
    "What was the Trail of Tears?",
    "Who was Tecumseh?",
    "What caused the Spanish-American War?",
    "Explain the Homestead Act.",
    "What was the Gold Rush of 1849?",
    "Who was Harriet Tubman?",
    "What caused the Panic of 1893?",
    "Explain the Reconstruction era.",
    "What was the Gilded Age?",
    "Who was Theodore Roosevelt?",
    "What caused the Triangle Fire?",
    "Explain the Progressive Era.",
    "What was the Roaring Twenties?",
    "Who was Woodrow Wilson?",
    "What caused Prohibition?",
    "Explain the New Deal.",
    "What was the Dust Bowl?",
    "Who was Franklin D. Roosevelt?",
    "What caused the attack on Pearl Harbor?",
    "Explain the Manhattan Project.",
    "What was D-Day?",
    "Who was Dwight D. Eisenhower?",
    "What caused the Bay of Pigs invasion?",
    "Explain the Gulf of Tonkin incident.",
    # --- Geography & Earth Science (100) ---
    "What is the capital of France?",
    "How do tectonic plates move?",
    "What causes earthquakes?",
    "How do volcanoes form?",
    "What is the water cycle?",
    "How does erosion shape landscapes?",
    "What causes tsunamis?",
    "How do hurricanes form?",
    "What is the ozone layer?",
    "How does climate differ from weather?",
    "What causes the seasons?",
    "How do glaciers move?",
    "What is the Mariana Trench?",
    "How does the Gulf Stream work?",
    "What causes tornadoes?",
    "How do coral reefs form?",
    "What is the ring of fire?",
    "How does a geyser work?",
    "What causes ocean currents?",
    "How do cave systems form?",
    "What is the Sahara Desert?",
    "How does the carbon cycle work?",
    "What causes landslides?",
    "How do rivers form deltas?",
    "What is the Great Barrier Reef?",
    "How does soil formation work?",
    "What causes sinkholes?",
    "How do mountains form?",
    "What is the Amazon Rainforest?",
    "How does the nitrogen cycle work?",
    "What causes avalanches?",
    "How do islands form?",
    "What is the Dead Sea?",
    "How does weathering break down rocks?",
    "What causes monsoons?",
    "How do atolls form?",
    "What is the Nile River?",
    "How does the rock cycle work?",
    "What causes droughts?",
    "How do fjords form?",
    "What is Lake Baikal?",
    "How does a watershed function?",
    "What causes El Nino?",
    "How do sand dunes form?",
    "What is the Antarctic ice sheet?",
    "How does ocean salinity vary?",
    "What causes La Nina?",
    "How do barrier islands form?",
    "What is the Gobi Desert?",
    "How does the phosphorus cycle work?",
    "What causes floods?",
    "How do mesas and buttes form?",
    "What is the Caspian Sea?",
    "How does groundwater flow?",
    "What causes hailstorms?",
    "How do oxbow lakes form?",
    "What is the Congo Basin?",
    "How does ocean acidification work?",
    "What causes blizzards?",
    "How do karst landscapes form?",
    "What is the Tibetan Plateau?",
    "How does desertification occur?",
    "What causes fog?",
    "How do estuaries form?",
    "What is the Great Rift Valley?",
    "How does thermal expansion affect sea level?",
    "What causes waterspouts?",
    "How do sea stacks form?",
    "What is the Atacama Desert?",
    "How does the sulfur cycle work?",
    "What causes dust storms?",
    "How do alluvial fans form?",
    "What is the Danube River?",
    "How does permafrost thaw affect climate?",
    "What causes ice storms?",
    "How do calderas form?",
    "What is the Ganges River?",
    "How does sedimentation work?",
    "What causes heat waves?",
    "How do geysers differ from hot springs?",
    "What is the Mississippi Delta?",
    "How does the hydrological cycle work?",
    "What causes storm surges?",
    "How do moraines form?",
    "What is the Bering Strait?",
    "How does albedo affect climate?",
    "What causes acid rain?",
    "How do terraces form on hillsides?",
    "What is the Strait of Gibraltar?",
    "How does deforestation affect rainfall?",
    "What causes thunder?",
    "How do natural arches form?",
    "What is the Yangtze River?",
    "How does ocean stratification work?",
    "What causes ball lightning?",
    "How do talus slopes form?",
    "What is the Volga River?",
    "How does the jet stream affect weather?",
    "What causes microbursts?",
    "How do pediments form?",
    # --- Creative Writing (100) ---
    "Write a short poem about a rainy day.",
    "Write a haiku about the ocean.",
    "Tell me a joke about cats.",
    "Write a limerick about a wizard.",
    "Compose a two-line rhyme about coffee.",
    "Write a short story opening about a storm.",
    "Create a riddle about the sun.",
    "Write a haiku about autumn leaves.",
    "Tell me a joke about programmers.",
    "Write a limerick about the moon.",
    "Compose a couplet about friendship.",
    "Write a short fable about a clever fox.",
    "Create a tongue twister about seashells.",
    "Write a haiku about snow.",
    "Tell me a joke about dogs.",
    "Write a limerick about a baker.",
    "Compose a rhyme about the stars.",
    "Write a micro story in exactly 50 words.",
    "Create a riddle about water.",
    "Write a haiku about spring.",
    "Tell me a joke about teachers.",
    "Write a limerick about a pirate.",
    "Compose a couplet about the wind.",
    "Write a short dialog between a cat and dog.",
    "Create a riddle about time.",
    "Write a haiku about winter.",
    "Tell me a joke about scientists.",
    "Write a limerick about a robot.",
    "Compose a rhyme about the rain.",
    "Write a tiny ghost story in 3 sentences.",
    "Create a riddle about a mirror.",
    "Write a haiku about summer.",
    "Tell me a joke about dentists.",
    "Write a limerick about a dragon.",
    "Compose a couplet about the sea.",
    "Write a short poem about courage.",
    "Create a riddle about fire.",
    "Write a haiku about a river.",
    "Tell me a joke about engineers.",
    "Write a limerick about a chef.",
    "Compose a rhyme about laughter.",
    "Write a tiny love story in 3 sentences.",
    "Create a riddle about the wind.",
    "Write a haiku about a mountain.",
    "Tell me a joke about lawyers.",
    "Write a limerick about a sailor.",
    "Compose a couplet about hope.",
    "Write a short poem about a sunset.",
    "Create a riddle about a book.",
    "Write a haiku about dawn.",
    "Tell me a joke about chefs.",
    "Write a limerick about a ghost.",
    "Compose a rhyme about dreams.",
    "Write a tiny mystery in 3 sentences.",
    "Create a riddle about a clock.",
    "Write a haiku about the forest.",
    "Tell me a joke about musicians.",
    "Write a limerick about a knight.",
    "Compose a couplet about silence.",
    "Write a short poem about the city.",
    "Create a riddle about ice.",
    "Write a haiku about the desert.",
    "Tell me a joke about pilots.",
    "Write a limerick about a witch.",
    "Compose a rhyme about thunder.",
    "Write a tiny adventure in 3 sentences.",
    "Create a riddle about a shadow.",
    "Write a haiku about a garden.",
    "Tell me a joke about accountants.",
    "Write a limerick about a mermaid.",
    "Compose a couplet about freedom.",
    "Write a short poem about midnight.",
    "Create a riddle about a key.",
    "Write a haiku about moonlight.",
    "Tell me a joke about athletes.",
    "Write a limerick about a troll.",
    "Compose a rhyme about the sunrise.",
    "Write a tiny comedy scene in 3 sentences.",
    "Create a riddle about an egg.",
    "Write a haiku about starlight.",
    "Tell me a joke about librarians.",
    "Write a limerick about an elf.",
    "Compose a couplet about memory.",
    "Write a short poem about a candle.",
    "Create a riddle about a river.",
    "Write a haiku about fog.",
    "Tell me a joke about artists.",
    "Write a limerick about a dwarf.",
    "Compose a rhyme about the moon.",
    "Write a tiny sci-fi scene in 3 sentences.",
    "Create a riddle about darkness.",
    "Write a haiku about a waterfall.",
    "Tell me a joke about astronauts.",
    "Write a limerick about a unicorn.",
    "Compose a couplet about patience.",
    "Write a short poem about the sea.",
    "Create a riddle about a candle.",
    "Write a haiku about a bridge.",
    "Tell me a joke about farmers.",
    "Write a limerick about a phoenix.",
    # --- Philosophy & Ethics (100) ---
    "What is the meaning of life?",
    "Explain the trolley problem.",
    "What is Plato's allegory of the cave?",
    "Explain utilitarianism.",
    "What is existentialism?",
    "Explain the categorical imperative.",
    "What is the social contract theory?",
    "Explain Descartes' cogito ergo sum.",
    "What is nihilism?",
    "Explain the concept of free will.",
    "What is determinism?",
    "Explain Occam's Razor.",
    "What is the Socratic method?",
    "Explain the ship of Theseus paradox.",
    "What is stoicism?",
    "Explain the concept of justice by Rawls.",
    "What is pragmatism in philosophy?",
    "Explain the is-ought problem.",
    "What is the problem of evil?",
    "Explain the veil of ignorance.",
    "What is moral relativism?",
    "Explain the prisoner's dilemma.",
    "What is epistemology?",
    "Explain the Euthyphro dilemma.",
    "What is phenomenology?",
    "Explain Pascal's Wager.",
    "What is virtue ethics?",
    "Explain the paradox of hedonism.",
    "What is the mind-body problem?",
    "Explain the Chinese Room argument.",
    "What is solipsism?",
    "Explain the Turing test.",
    "What is logical positivism?",
    "Explain the naturalistic fallacy.",
    "What is the correspondence theory of truth?",
    "Explain the theory of forms.",
    "What is the coherence theory of truth?",
    "Explain the Ring of Gyges thought experiment.",
    "What is the pragmatic theory of truth?",
    "Explain the experience machine.",
    "What is compatibilism?",
    "Explain the Mary's Room thought experiment.",
    "What is libertarianism in philosophy?",
    "Explain the zombie argument.",
    "What is hard determinism?",
    "Explain the vat brain thought experiment.",
    "What is deontological ethics?",
    "Explain the repugnant conclusion.",
    "What is consequentialism?",
    "Explain the mere addition paradox.",
    "What is moral realism?",
    "Explain the open question argument.",
    "What is moral anti-realism?",
    "Explain the fact-value distinction.",
    "What is ethical egoism?",
    "Explain the doctrine of double effect.",
    "What is moral luck?",
    "Explain the lottery paradox.",
    "What is epistemic humility?",
    "Explain the Gettier problem.",
    "What is the regress argument?",
    "Explain coherentism in epistemology.",
    "What is foundationalism?",
    "Explain the problem of induction.",
    "What is reliabilism?",
    "Explain the Duhem-Quine thesis.",
    "What is contextualism?",
    "Explain the preface paradox.",
    "What is invariantism?",
    "Explain the surprise examination paradox.",
    "What is internalism in epistemology?",
    "Explain the frame problem in AI.",
    "What is externalism in epistemology?",
    "Explain the symbol grounding problem.",
    "What is the problem of other minds?",
    "Explain the binding problem.",
    "What is panpsychism?",
    "Explain the hard problem of consciousness.",
    "What is epiphenomenalism?",
    "Explain the explanatory gap.",
    "What is functionalism in philosophy of mind?",
    "Explain multiple realizability.",
    "What is identity theory of mind?",
    "Explain anomalous monism.",
    "What is eliminative materialism?",
    "Explain the knowledge argument.",
    "What is property dualism?",
    "Explain supervenience.",
    "What is neutral monism?",
    "Explain the combination problem.",
    "What is substance dualism?",
    "Explain the interaction problem.",
    "What is dual-aspect monism?",
    "Explain occasionalism.",
    "What is parallelism in philosophy?",
    "Explain pre-established harmony.",
    "What is idealism in philosophy?",
    "Explain transcendental idealism.",
    "What is subjective idealism?",
    "Explain objective idealism.",
    # --- Health & Fitness (50) ---
    "What are the benefits of exercise?",
    "How does sleep affect health?",
    "What is the Mediterranean diet?",
    "How does stress affect the body?",
    "What are the benefits of meditation?",
    "How does hydration affect performance?",
    "What is interval training?",
    "How does yoga improve flexibility?",
    "What are the benefits of walking daily?",
    "How does caffeine affect the body?",
    "What is the importance of stretching?",
    "How does alcohol affect sleep quality?",
    "What are the benefits of swimming?",
    "How does posture affect back pain?",
    "What is the importance of rest days?",
    "How does sugar affect energy levels?",
    "What are the benefits of cycling?",
    "How does cold exposure affect the body?",
    "What is the importance of core strength?",
    "How does screen time affect eye health?",
    "What are the benefits of resistance training?",
    "How does nutrition affect muscle recovery?",
    "What is the importance of warm-up exercises?",
    "How does breathing technique affect exercise?",
    "What are the benefits of outdoor exercise?",
    "How does sleep deprivation affect cognition?",
    "What is the importance of protein intake?",
    "How does chronic pain affect daily life?",
    "What are the benefits of tai chi?",
    "How does music affect workout performance?",
    "What is the importance of bone density?",
    "How does aging affect muscle mass?",
    "What are the benefits of Pilates?",
    "How does fiber intake affect digestion?",
    "What is the importance of joint mobility?",
    "How does vitamin C support immunity?",
    "What are the benefits of deep breathing?",
    "How does omega-3 fatty acid help health?",
    "What is the importance of electrolytes?",
    "How does magnesium affect sleep?",
    "What are the benefits of foam rolling?",
    "How does zinc support immune function?",
    "What is the importance of hip mobility?",
    "How does B12 deficiency affect energy?",
    "What are the benefits of cold showers?",
    "How does turmeric reduce inflammation?",
    "What is the importance of grip strength?",
    "How does probiotics affect gut health?",
    "What are the benefits of sauna use?",
    "How does creatine affect performance?",
    # --- Economics & Business (50) ---
    "What is supply and demand?",
    "How does inflation work?",
    "What is GDP?",
    "Explain the stock market basics.",
    "What is a recession?",
    "How do interest rates affect the economy?",
    "What is the Federal Reserve?",
    "Explain the concept of opportunity cost.",
    "What is a trade deficit?",
    "How does currency exchange work?",
    "What is fiscal policy?",
    "Explain the concept of elasticity.",
    "What is monetary policy?",
    "How does a central bank set rates?",
    "What is quantitative easing?",
    "Explain the Phillips curve.",
    "What is a budget deficit?",
    "How does trade affect GDP?",
    "What is comparative advantage?",
    "Explain the Laffer curve.",
    "What is the multiplier effect?",
    "How does a bond market work?",
    "What is a yield curve?",
    "Explain the concept of sunk cost.",
    "What is a market bubble?",
    "How does venture capital work?",
    "What is an IPO?",
    "Explain the concept of marginal cost.",
    "What is a hedge fund?",
    "How does compound interest work?",
    "What is a mutual fund?",
    "Explain the concept of diversification.",
    "What is a credit default swap?",
    "How does short selling work?",
    "What is a futures contract?",
    "Explain the efficient market hypothesis.",
    "What is a Ponzi scheme?",
    "How does bankruptcy work?",
    "What is a leveraged buyout?",
    "Explain the concept of amortization.",
    "What is a convertible bond?",
    "How does a REIT work?",
    "What is an ETF?",
    "Explain the concept of market cap.",
    "What is a stock split?",
    "How does dividend investing work?",
    "What is a bear market?",
    "Explain the concept of liquidity.",
    "What is a bull market?",
    "How does dollar cost averaging work?",
    # --- Space & Astronomy (50) ---
    "How far is the Moon from Earth?",
    "What is a light year?",
    "How many planets are in the solar system?",
    "What is the Milky Way galaxy?",
    "How does a rocket engine work?",
    "What is the International Space Station?",
    "How do astronauts live in space?",
    "What is the Kuiper Belt?",
    "How does a satellite orbit Earth?",
    "What is the Oort Cloud?",
    "How do we detect exoplanets?",
    "What is the James Webb Space Telescope?",
    "How does the Sun produce energy?",
    "What is a solar eclipse?",
    "How do comets differ from asteroids?",
    "What is the asteroid belt?",
    "How does GPS rely on satellites?",
    "What is a geosynchronous orbit?",
    "How do space probes explore planets?",
    "What is the Voyager mission?",
    "How does the Hubble telescope work?",
    "What is the Drake equation?",
    "How does spacewalking work?",
    "What is the Fermi paradox?",
    "How does reentry heating work?",
    "What is Lagrange point?",
    "How does a solar sail work?",
    "What is the Kardashev scale?",
    "How does ion propulsion work?",
    "What is the cosmic distance ladder?",
    "How does a space elevator concept work?",
    "What is the Chandrasekhar mass?",
    "How does stellar nucleosynthesis work?",
    "What is a planetary nebula?",
    "How does binary star system work?",
    "What is a protoplanetary disk?",
    "How does gravitational slingshot work?",
    "What is a Kuiper Belt object?",
    "How does the solar wind work?",
    "What is a magnetosphere?",
    "How does a solar flare affect Earth?",
    "What is a coronal mass ejection?",
    "How does the Van Allen belt protect us?",
    "What is the heliosphere?",
    "How does a star die?",
    "What is a Type Ia supernova?",
    "How does a gamma ray burst occur?",
    "What is dark energy?",
    "How does cosmic expansion work?",
    "What is the observable universe?",
    # --- Food & Cooking (50) ---
    "How do you make a basic tomato sauce?",
    "What is the Maillard reaction?",
    "How does fermentation work in bread?",
    "What is the difference between baking and roasting?",
    "How do you properly season a cast iron pan?",
    "What is emulsification in cooking?",
    "How does caramelization work?",
    "What is the difference between stock and broth?",
    "How do you make a roux?",
    "What is sous vide cooking?",
    "How does gluten develop in dough?",
    "What is the smoke point of olive oil?",
    "How do you temper chocolate?",
    "What is the difference between jam and jelly?",
    "How does brining affect meat?",
    "What is the role of acid in cooking?",
    "How do you make a proper vinaigrette?",
    "What is the importance of resting meat?",
    "How does pressure cooking work?",
    "What is the five mother sauces?",
    "How do you properly dice an onion?",
    "What is the difference between herbs and spices?",
    "How does yeast make bread rise?",
    "What is the purpose of deglazing a pan?",
    "How do you make homemade pasta?",
    "What is the importance of mise en place?",
    "How does smoking preserve food?",
    "What is the difference between sauteing and frying?",
    "How do you make a proper meringue?",
    "What is blanching and why is it used?",
    "How does curing preserve meat?",
    "What is the role of salt in baking?",
    "How do you make a basic white sauce?",
    "What is the difference between puree and coulis?",
    "How does pickling preserve vegetables?",
    "What is the role of eggs in baking?",
    "How do you make a basic bread dough?",
    "What is the difference between boiling and simmering?",
    "How does an air fryer work?",
    "What is the role of fat in pastry?",
    "How do you make a basic pizza dough?",
    "What is the difference between braising and stewing?",
    "How does a convection oven differ?",
    "What is the role of sugar in baking?",
    "How do you make a basic risotto?",
    "What is the difference between grilling and broiling?",
    "How does a slow cooker work?",
    "What is the role of butter in cooking?",
    "How do you make a basic soup stock?",
    "What is the difference between poaching and steaming?",
    # --- Music & Art (50) ---
    "What is the difference between major and minor keys?",
    "How does a piano produce sound?",
    "What is the golden ratio in art?",
    "How does a violin make different pitches?",
    "What is counterpoint in music?",
    "How does perspective work in drawing?",
    "What is sonata form?",
    "How does color theory work in painting?",
    "What is a fugue in music?",
    "How does chiaroscuro create depth?",
    "What is the pentatonic scale?",
    "How does pointillism create images?",
    "What is a time signature?",
    "How does fresco painting work?",
    "What is a chord progression?",
    "How does lithography work?",
    "What is syncopation?",
    "How does watercolor differ from oil paint?",
    "What is a cadence in music?",
    "How does sculpture casting work?",
    "What is a leitmotif?",
    "How does woodcut printing work?",
    "What is polyrhythm?",
    "How does encaustic painting work?",
    "What is a bridge in a song?",
    "How does glassblowing work?",
    "What is a coda in music?",
    "How does intaglio printing work?",
    "What is an arpeggio?",
    "How does mosaic art work?",
    "What is a fermata?",
    "How does batik dyeing work?",
    "What is a glissando?",
    "How does pottery glazing work?",
    "What is a crescendo?",
    "How does screen printing work?",
    "What is a staccato?",
    "How does etching work?",
    "What is a tremolo?",
    "How does calligraphy differ from lettering?",
    "What is a vibrato?",
    "How does collage art work?",
    "What is an ostinato?",
    "How does papier-mache work?",
    "What is a riff in music?",
    "How does textile weaving work?",
    "What is a motif in music?",
    "How does relief sculpture work?",
    "What is an interval in music?",
    "How does origami folding work?",
    # --- Animals & Nature (50) ---
    "How do bees make honey?",
    "What is the fastest animal on Earth?",
    "How do birds navigate during migration?",
    "What is the deepest ocean creature?",
    "How do chameleons change color?",
    "What is the tallest tree species?",
    "How do dolphins communicate?",
    "What is the largest land animal?",
    "How do spiders spin webs?",
    "What is the smallest mammal?",
    "How do salmon find their birth river?",
    "What is the longest living animal?",
    "How do octopuses camouflage?",
    "What is the fastest bird?",
    "How do ants organize their colonies?",
    "What is the largest ocean predator?",
    "How do fireflies produce light?",
    "What is the strongest animal by weight?",
    "How do elephants communicate?",
    "What is the most venomous snake?",
    "How do whales sleep?",
    "What is the smartest non-primate animal?",
    "How do penguins survive extreme cold?",
    "What is the largest insect?",
    "How do starfish regenerate limbs?",
    "What is the fastest fish?",
    "How do owls hunt at night?",
    "What is the most colorful bird?",
    "How do sea turtles navigate oceans?",
    "What is the largest species of shark?",
    "How do wolves hunt in packs?",
    "What is the most intelligent bird?",
    "How do coral polyps build reefs?",
    "What is the loudest animal?",
    "How do arctic foxes survive winter?",
    "What is the most dangerous jellyfish?",
    "How do homing pigeons find their way?",
    "What is the smallest bird?",
    "How do electric eels generate electricity?",
    "What is the oldest living tree?",
    "How do monarch butterflies migrate?",
    "What is the fastest marine mammal?",
    "How do woodpeckers avoid brain injury?",
    "What is the most intelligent insect?",
    "How do deep sea fish survive pressure?",
    "What is the largest wingspan of a bird?",
    "How do beavers build dams?",
    "What is the most camouflaged animal?",
    "How do platypuses detect prey?",
    "What is the most resilient organism?",
    # --- Language & Linguistics (50) ---
    "How many languages are spoken worldwide?",
    "What is the most spoken language?",
    "How does language acquisition work?",
    "What is the Sapir-Whorf hypothesis?",
    "How do sign languages differ globally?",
    "What is the origin of the English language?",
    "How does pidgin become a creole?",
    "What is the most difficult language to learn?",
    "How does bilingualism affect the brain?",
    "What is the International Phonetic Alphabet?",
    "How do tonal languages work?",
    "What is the oldest written language?",
    "How does language change over time?",
    "What is a dead language?",
    "How do constructed languages work?",
    "What is the difference between dialect and language?",
    "How does machine translation work?",
    "What is etymology?",
    "How do children learn grammar?",
    "What is a lingua franca?",
    "How does code-switching work?",
    "What is morphology in linguistics?",
    "How do writing systems develop?",
    "What is syntax in linguistics?",
    "How does semantic change happen?",
    "What is pragmatics in language?",
    "How do loanwords enter a language?",
    "What is phonology?",
    "How does language influence thought?",
    "What is sociolinguistics?",
    "How do onomatopoeia differ across languages?",
    "What is a phoneme?",
    "How does language extinction happen?",
    "What is a morpheme?",
    "How do languages borrow grammar?",
    "What is an agglutinative language?",
    "How does diglossia work?",
    "What is an isolating language?",
    "How do speech registers differ?",
    "What is a fusional language?",
    "How does language planning work?",
    "What is a polysynthetic language?",
    "How do euphemisms develop?",
    "What is historical linguistics?",
    "How does grammaticalization work?",
    "What is comparative linguistics?",
    "How do taboo words change over time?",
    "What is computational linguistics?",
    "How does prosody affect meaning?",
    "What is corpus linguistics?",
    # --- Psychology (50) ---
    "What is cognitive dissonance?",
    "How does memory formation work?",
    "What is the placebo effect?",
    "How does classical conditioning work?",
    "What is the bystander effect?",
    "How does operant conditioning work?",
    "What is confirmation bias?",
    "How does learned helplessness develop?",
    "What is the Dunning-Kruger effect?",
    "How does attachment theory work?",
    "What is the halo effect?",
    "How does intrinsic motivation differ?",
    "What is the anchoring bias?",
    "How does groupthink occur?",
    "What is the availability heuristic?",
    "How does the mere exposure effect work?",
    "What is the fundamental attribution error?",
    "How does cognitive behavioral therapy work?",
    "What is the spotlight effect?",
    "How does positive reinforcement work?",
    "What is the Milgram experiment?",
    "How does the Stanford prison experiment relate?",
    "What is the Asch conformity experiment?",
    "How does the peak-end rule work?",
    "What is the Zeigarnik effect?",
    "How does selective attention work?",
    "What is the cocktail party effect?",
    "How does priming affect behavior?",
    "What is the endowment effect?",
    "How does the framing effect work?",
    "What is the sunk cost fallacy?",
    "How does the bandwagon effect work?",
    "What is the decoy effect?",
    "How does the IKEA effect work?",
    "What is the serial position effect?",
    "How does the spacing effect work?",
    "What is the testing effect?",
    "How does interleaving improve learning?",
    "What is the generation effect?",
    "How does elaborative rehearsal work?",
    "What is the self-reference effect?",
    "How does the picture superiority effect work?",
    "What is the levels of processing theory?",
    "How does context-dependent memory work?",
    "What is state-dependent memory?",
    "How does mood congruent memory work?",
    "What is the misinformation effect?",
    "How does source monitoring error occur?",
    "What is the DRM paradigm?",
    "How does imagination inflation work?",
    # --- Miscellaneous & Trivia (60) ---
    "Why is the sky blue?",
    "How does a microwave oven heat food?",
    "Why do we dream?",
    "How does soap clean things?",
    "Why do leaves change color in fall?",
    "How does a refrigerator work?",
    "Why do we yawn?",
    "How does a touchscreen detect fingers?",
    "Why is the ocean salty?",
    "How does Wi-Fi transmit data?",
    "Why do onions make you cry?",
    "How does a zipper work?",
    "Why do stars twinkle?",
    "How does a battery store energy?",
    "Why does ice float on water?",
    "How does a light bulb work?",
    "Why does metal feel cold to the touch?",
    "How does a compass work?",
    "Why do we get hiccups?",
    "How does a lock and key mechanism work?",
    "Why does the Moon appear larger at horizon?",
    "How does a bicycle stay upright?",
    "Why do we get goosebumps?",
    "How does a smoke detector work?",
    "Why does helium change your voice?",
    "How does a thermos keep drinks hot?",
    "Why do we blush?",
    "How does a wind turbine generate power?",
    "Why do cats purr?",
    "How does a sewing machine work?",
    "Why do we sneeze?",
    "How does a parachute slow descent?",
    "Why do wounds itch when healing?",
    "How does a submarine dive and surface?",
    "Why do we get brain freeze?",
    "How does a hot air balloon fly?",
    "Why do we get deja vu?",
    "How does a hydraulic press work?",
    "Why do fingers wrinkle in water?",
    "How does a pendulum clock keep time?",
    "Why do we get motion sickness?",
    "How does an elevator work?",
    "Why do we get static electricity?",
    "How does a water filter purify water?",
    "Why do we have fingerprints?",
    "How does an air conditioner work?",
    "Why do we feel pain?",
    "How does a suspension bridge work?",
    "Why do we have eyebrows?",
    "How does a 3D printer work?",
    "Why do rubber bands stretch?",
    "How does a fuel cell work?",
    "Why do we get jet lag?",
    "How does a catalytic converter work?",
    "Why do balloons pop?",
    "How does a nuclear submarine work?",
    "Why do we get nosebleeds?",
    "How does a defibrillator work?",
    "Why do we get charley horses?",
    "How does a hologram work?",
]

if __name__ == "__main__":
    main()
