include(FetchContent)
find_path(NEXUS_HTTPLIB_INCLUDE_DIR httplib.h)
if(NEXUS_HTTPLIB_INCLUDE_DIR)
    file(STRINGS "${NEXUS_HTTPLIB_INCLUDE_DIR}/httplib.h" _version REGEX "^#define CPPHTTPLIB_VERSION ")
    string(REGEX MATCH "[0-9]+\\.[0-9]+\\.[0-9]+" _version "${_version}")
    if(_version VERSION_GREATER_EQUAL "0.18.3")
        add_library(nexus-httplib INTERFACE)
        add_library(httplib::httplib ALIAS nexus-httplib)
        target_include_directories(nexus-httplib INTERFACE "${NEXUS_HTTPLIB_INCLUDE_DIR}")
        target_compile_definitions(nexus-httplib INTERFACE CPPHTTPLIB_OPENSSL_SUPPORT)
        target_link_libraries(nexus-httplib INTERFACE OpenSSL::SSL OpenSSL::Crypto)
        return()
    endif()
endif()
FetchContent_Declare(httplib
    GIT_REPOSITORY https://github.com/yhirose/cpp-httplib.git
    GIT_TAG v0.18.3)
set(HTTPLIB_REQUIRE_OPENSSL ON CACHE BOOL "" FORCE)
set(HTTPLIB_USE_BROTLI_IF_AVAILABLE OFF CACHE BOOL "" FORCE)
set(HTTPLIB_USE_ZLIB_IF_AVAILABLE ON CACHE BOOL "" FORCE)
set(HTTPLIB_INSTALL OFF CACHE BOOL "" FORCE)
FetchContent_MakeAvailable(httplib)
