#!/bin/bash

# Create the llama directory in user space
# This ensures that llama.cpp can be installed to the user application directory

INSTALL_DIR="$HOME/Library/Application Support/Lemonade"
LLAMA_DIR="${INSTALL_DIR}/llama"

# Create directory if it doesn't exist
mkdir -p "$LLAMA_DIR"

# Always set correct permissions (even if directory already existed)
chmod 755 "$LLAMA_DIR"

exit 0
