name: 'Setup Python'
description: 'Install Python on self-hosted runners. Uses embeddable Python on Windows, checks system Python on Linux.'

inputs:
  python-version:
    description: 'Python version to install (e.g., 3.10, 3.12)'
    required: false
    default: '3.10'

outputs:
  python-path:
    description: 'Path to the Python executable'
    value: ${{ steps.setup.outputs.python-path }}

runs:
  using: "composite"
  steps:
    - name: Setup Python
      id: setup
      shell: bash
      run: |
        PYTHON_VERSION="${{ inputs.python-version }}"
        
        echo "Setting up Python $PYTHON_VERSION..."
        
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          # Windows: Use embeddable Python from python.org
          # Map version to download URL
          case "$PYTHON_VERSION" in
            "3.10")
              PYTHON_FULL="3.10.11"
              ;;
            "3.11")
              PYTHON_FULL="3.11.9"
              ;;
            "3.12")
              PYTHON_FULL="3.12.7"
              ;;
            "3.13")
              PYTHON_FULL="3.13.0"
              ;;
            *)
              echo "Unsupported Python version: $PYTHON_VERSION"
              exit 1
              ;;
          esac
          
          PYTHON_DIR="$GITHUB_WORKSPACE/.python-$PYTHON_VERSION"
          PYTHON_EXE="$PYTHON_DIR/python.exe"
          
          # Check if already installed
          if [ -f "$PYTHON_EXE" ]; then
            echo "Python $PYTHON_VERSION already available at $PYTHON_DIR"
          else
            echo "Downloading Python $PYTHON_FULL embeddable..."
            PYTHON_URL="https://www.python.org/ftp/python/${PYTHON_FULL}/python-${PYTHON_FULL}-embed-amd64.zip"
            
            mkdir -p "$PYTHON_DIR"
            curl -sSL "$PYTHON_URL" -o "$PYTHON_DIR/python.zip"
            unzip -q "$PYTHON_DIR/python.zip" -d "$PYTHON_DIR"
            rm "$PYTHON_DIR/python.zip"
            
            # Enable pip in embeddable Python by uncommenting import site
            PTH_FILE="$PYTHON_DIR/python${PYTHON_VERSION//./}._pth"
            if [ -f "$PTH_FILE" ]; then
              sed -i 's/#import site/import site/' "$PTH_FILE"
            fi
            
            # Install pip
            echo "Installing pip..."
            curl -sSL https://bootstrap.pypa.io/get-pip.py -o "$PYTHON_DIR/get-pip.py"
            "$PYTHON_EXE" "$PYTHON_DIR/get-pip.py" --no-warn-script-location
            rm "$PYTHON_DIR/get-pip.py"
            
            echo "Python $PYTHON_FULL installed at $PYTHON_DIR"
          fi
          
          # Add to PATH for subsequent steps
          echo "$PYTHON_DIR" >> $GITHUB_PATH
          echo "$PYTHON_DIR/Scripts" >> $GITHUB_PATH
          
          # Convert to Windows path for output
          PYTHON_PATH=$(cygpath -w "$PYTHON_EXE")
          echo "python-path=$PYTHON_PATH" >> $GITHUB_OUTPUT
          
        elif [[ "$RUNNER_OS" == "Linux" ]]; then
          # Linux: Check system Python or install if needed
          REQUIRED_MAJOR=$(echo $PYTHON_VERSION | cut -d. -f1)
          REQUIRED_MINOR=$(echo $PYTHON_VERSION | cut -d. -f2)
          
          # Try python3.X first, then python3, then python
          PYTHON_CMD=""
          for cmd in "python$PYTHON_VERSION" "python3" "python"; do
            if command -v "$cmd" &> /dev/null; then
              VERSION=$("$cmd" --version 2>&1 | grep -oP '\d+\.\d+' | head -1)
              MAJOR=$(echo $VERSION | cut -d. -f1)
              MINOR=$(echo $VERSION | cut -d. -f2)
              
              if [[ "$MAJOR" == "$REQUIRED_MAJOR" && "$MINOR" == "$REQUIRED_MINOR" ]]; then
                PYTHON_CMD=$(command -v "$cmd")
                echo "Found matching Python: $PYTHON_CMD (version $VERSION)"
                break
              elif [[ "$MAJOR" == "$REQUIRED_MAJOR" && "$MINOR" -ge "$REQUIRED_MINOR" ]]; then
                PYTHON_CMD=$(command -v "$cmd")
                echo "Found compatible Python: $PYTHON_CMD (version $VERSION, requested $PYTHON_VERSION)"
                break
              fi
            fi
          done
          
          if [ -z "$PYTHON_CMD" ]; then
            # Try to install from deadsnakes PPA (Ubuntu) or system package manager
            echo "Python $PYTHON_VERSION not found. Attempting to install..."
            
            if command -v apt-get &> /dev/null; then
              sudo add-apt-repository -y ppa:deadsnakes/ppa 2>/dev/null || true
              sudo apt-get update
              sudo apt-get install -y "python${PYTHON_VERSION}" "python${PYTHON_VERSION}-venv" "python${PYTHON_VERSION}-pip" || {
                echo "Failed to install Python $PYTHON_VERSION from deadsnakes"
                echo "Falling back to system python3..."
                PYTHON_CMD=$(command -v python3)
              }
              PYTHON_CMD=$(command -v "python${PYTHON_VERSION}") || PYTHON_CMD=$(command -v python3)
            else
              PYTHON_CMD=$(command -v python3)
            fi
          fi
          
          if [ -z "$PYTHON_CMD" ]; then
            echo "ERROR: Could not find or install Python $PYTHON_VERSION"
            exit 1
          fi
          
          echo "python-path=$PYTHON_CMD" >> $GITHUB_OUTPUT
          "$PYTHON_CMD" --version
          
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          # macOS: Use system Python or install via python.org
          PYTHON_CMD=$(command -v "python$PYTHON_VERSION" || command -v python3)
          
          if [ -z "$PYTHON_CMD" ]; then
            echo "Python not found on macOS. Please install Python $PYTHON_VERSION manually."
            exit 1
          fi
          
          echo "python-path=$PYTHON_CMD" >> $GITHUB_OUTPUT
          "$PYTHON_CMD" --version
        fi

    - name: Verify Python (Windows)
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        $pythonPath = "${{ steps.setup.outputs.python-path }}"
        if ($pythonPath) {
          & $pythonPath --version
          & $pythonPath -m pip --version
        } else {
          python --version
          python -m pip --version
        }

