"use client";

import {
  AlertTriangle,
  FileText,
  RefreshCw,
  Trash2,
  X,
} from "lucide-react";
import Link from "next/link";
import { useCallback, useRef, useState } from "react";
import { useLemonade } from "@/components/providers/LemonadeProvider";
import { useToast } from "@/components/providers/ToastProvider";
import { UploadZone } from "@/components/documents/UploadZone";
import {
  Callout,
  Card,
  Chip,
  EmptyState,
  PageHeader,
  ProgressBar,
  SkeletonList,
} from "@/components/ui/Primitives";
import { deleteAllData, deleteDocument, getChunks } from "@/lib/db/repo";
import { formatBytes } from "@/lib/documents/limits";
import { processFile, rebuildEmbeddings, type ProcessingProgress } from "@/lib/documents/process";
import { useDocuments } from "@/lib/hooks/useDocuments";
import { documentHref } from "@/lib/lemonade/client";
import { isLemonadeError } from "@/lib/lemonade/errors";
import { formatDuration, formatTimestamp } from "@/lib/utils/cn";

export default function DocumentsPage() {
  const { client, embeddingModel, isReady, status, beginRequest } = useLemonade();
  const { documents, activeDocumentId, setActiveDocumentId, loading, reload } = useDocuments();
  const toast = useToast();

  const [progress, setProgress] = useState<ProcessingProgress | null>(null);
  const [busy, setBusy] = useState(false);
  const abortRef = useRef<AbortController | null>(null);

  const runProcessing = useCallback(
    async (work: (signal: AbortSignal) => Promise<void>) => {
      const controller = new AbortController();
      abortRef.current = controller;
      const endRequest = beginRequest();
      setBusy(true);
      try {
        await work(controller.signal);
      } catch (error) {
        if (isLemonadeError(error) && error.kind === "cancelled") {
          toast.info("Processing cancelled.");
        } else {
          toast.error(
            isLemonadeError(error) ? error.displayMessage : (error as Error).message,
          );
        }
      } finally {
        endRequest();
        setBusy(false);
        setProgress(null);
        abortRef.current = null;
        await reload();
      }
    },
    [beginRequest, reload, toast],
  );

  const handleFile = useCallback(
    (file: File) => {
      if (!embeddingModel) return;
      void runProcessing(async (signal) => {
        const result = await processFile(file, {
          client,
          embeddingModel,
          signal,
          onProgress: setProgress,
        });
        await setActiveDocumentId(result.document.id);
        toast.success(
          `${result.document.filename} processed — ${result.document.pageCount} pages, ${result.document.chunkCount} chunks embedded locally.`,
        );
      });
    },
    [client, embeddingModel, runProcessing, setActiveDocumentId, toast],
  );

  const handleRebuild = useCallback(
    (documentId: string) => {
      if (!embeddingModel) return;
      void runProcessing(async (signal) => {
        const document = documents.find((doc) => doc.id === documentId);
        if (!document) return;
        const chunks = await getChunks(documentId);
        await rebuildEmbeddings(document, chunks, {
          client,
          embeddingModel,
          signal,
          onProgress: setProgress,
        });
        toast.success(`Embeddings rebuilt with ${embeddingModel}.`);
      });
    },
    [client, documents, embeddingModel, runProcessing, toast],
  );

  const handleDelete = useCallback(
    async (documentId: string, filename: string) => {
      if (!window.confirm(`Delete "${filename}" and everything derived from it?`)) return;
      await deleteDocument(documentId);
      await reload();
      toast.success(`${filename} deleted from local storage.`);
    },
    [reload, toast],
  );

  const handleDeleteAll = useCallback(async () => {
    if (
      !window.confirm(
        "Delete all local data? This removes every document, chunk, embedding, chat, extraction and benchmark from this browser.",
      )
    ) {
      return;
    }
    await deleteAllData();
    await reload();
    toast.success("All local data deleted.");
  }, [reload, toast]);

  const uploadDisabledReason = !isReady
    ? status === "connected"
      ? "Choose a chat model and an embedding model on the Setup page before uploading."
      : "Connect to Lemonade Server on the Setup page before uploading."
    : undefined;

  return (
    <>
      <PageHeader
        title="Documents"
        description="Upload a notice, circular, timetable or course PDF. Extraction and storage happen in your browser; embeddings are generated by your local Lemonade Server."
        actions={
          documents.length > 0 ? (
            <button type="button" className="btn-ghost text-danger" onClick={() => void handleDeleteAll()}>
              <Trash2 className="h-4 w-4" aria-hidden />
              Delete all local data
            </button>
          ) : null
        }
      />

      <div className="flex flex-col gap-6">
        <UploadZone onFile={handleFile} disabled={!isReady || busy} disabledReason={uploadDisabledReason} />

        {progress ? (
          <Card>
            <div className="flex items-start justify-between gap-4">
              <div className="min-w-0 flex-1">
                <ProgressBar
                  value={progress.percent ?? 0}
                  label={progress.message}
                />
                {progress.percent === null ? (
                  <p className="mt-2 text-xs text-ink-muted">Working…</p>
                ) : null}
              </div>
              <button
                type="button"
                className="btn-ghost shrink-0"
                onClick={() => abortRef.current?.abort()}
              >
                <X className="h-4 w-4" aria-hidden />
                Cancel
              </button>
            </div>
          </Card>
        ) : null}

        {loading ? (
          <SkeletonList rows={2} />
        ) : documents.length === 0 ? (
          <EmptyState
            icon={<FileText className="h-8 w-8" aria-hidden />}
            title="No documents yet"
            description="Upload a PDF, TXT or Markdown file to get started. Three fictional sample notices ship with this project in the samples/ folder."
          />
        ) : (
          <ul className="flex flex-col gap-3">
            {documents.map((document) => {
              const active = document.id === activeDocumentId;
              return (
                <Card key={document.id} as="li" className={active ? "border-brand" : undefined}>
                  <div className="flex flex-wrap items-start justify-between gap-3">
                    <div className="min-w-0 flex-1">
                      <div className="flex flex-wrap items-center gap-2">
                        <Link
                          href={documentHref(document.id)}
                          className="truncate text-sm font-semibold text-ink hover:underline"
                        >
                          {document.filename}
                        </Link>
                        {active ? <Chip tone="brand">Selected</Chip> : null}
                        <Chip tone={document.status === "embedded" ? "positive" : "caution"}>
                          {document.status === "embedded" ? "Embedded" : "Not embedded"}
                        </Chip>
                      </div>

                      <p className="mt-1.5 text-xs text-ink-muted">
                        {document.pageCount} pages · {document.chunkCount} chunks ·{" "}
                        {document.totalChars.toLocaleString()} chars · {formatBytes(document.sizeBytes)} ·{" "}
                        added {formatTimestamp(document.createdAt)}
                      </p>
                      <p className="mt-1 text-xs text-ink-faint">
                        Extraction {formatDuration(document.timings.extractionMs)} · chunking{" "}
                        {formatDuration(document.timings.chunkingMs)} · embedding{" "}
                        {formatDuration(document.timings.embeddingMs)}
                        {document.embeddingModel ? ` · ${document.embeddingModel}` : ""}
                        {document.embeddingDimensions ? ` (${document.embeddingDimensions}d)` : ""}
                      </p>

                      {document.warnings.length > 0 ? (
                        <ul className="mt-2 flex flex-col gap-1">
                          {document.warnings.map((warning) => (
                            <li key={warning} className="flex gap-1.5 text-xs text-caution">
                              <AlertTriangle className="mt-0.5 h-3.5 w-3.5 shrink-0" aria-hidden />
                              {warning}
                            </li>
                          ))}
                        </ul>
                      ) : null}
                    </div>

                    <div className="flex shrink-0 flex-wrap gap-2">
                      {!active ? (
                        <button
                          type="button"
                          className="btn-ghost"
                          onClick={() => void setActiveDocumentId(document.id)}
                        >
                          Select
                        </button>
                      ) : null}
                      <button
                        type="button"
                        className="btn-ghost"
                        disabled={busy || !embeddingModel}
                        onClick={() => handleRebuild(document.id)}
                        title="Re-run embeddings with the currently selected embedding model"
                      >
                        <RefreshCw className="h-4 w-4" aria-hidden />
                        Rebuild
                      </button>
                      <button
                        type="button"
                        className="btn-ghost text-danger"
                        onClick={() => void handleDelete(document.id, document.filename)}
                      >
                        <Trash2 className="h-4 w-4" aria-hidden />
                        Delete
                      </button>
                    </div>
                  </div>
                </Card>
              );
            })}
          </ul>
        )}

        <Callout title="Reprocessing a document">
          To reprocess from the original file — for example after switching to a different
          embedding model — upload it again, or use <strong>Rebuild</strong> to re-embed the stored
          chunks without re-reading the file.
        </Callout>
      </div>
    </>
  );
}
