#include "lemon/backends/vllm_omni/vllm_omni_server.h"
#include "lemon/backends/vllm_omni/vllm_omni.h"
#include "lemon/backends/backend_registry.h"
#include "lemon/backends/backend_utils.h"
#include "lemon/model_manager.h"
#include "lemon/runtime_config.h"
#include "lemon/system_info.h"
#include "lemon/utils/custom_args.h"
#include "lemon/utils/http_client.h"
#include "lemon/utils/json_utils.h"
#include "lemon/utils/path_utils.h"
#include "lemon/utils/process_manager.h"
#include <lemon/utils/aixlog.hpp>
#include <chrono>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <random>
#include <set>
#include <sstream>

namespace fs = std::filesystem;
using namespace lemon::utils;

namespace lemon {
namespace backends {

// Omni first-boot is slow: 3 stage engine cores + multimodal weight load +
// per-kernel Triton JIT for the gfx target. Give generous headroom.
static constexpr long VLLM_OMNI_READY_TIMEOUT_SECONDS = 1800;

// --- ROCm startup shim (mirrors the vllm backend) ---------------------------
// Disables vLLM's pynvml probe so it does not activate the CUDA platform plugin
// on hybrid AMD/NVIDIA hosts. ROCm PyTorch exposes HIP devices via
// torch.cuda/torch.accelerator, so no CUDA_VISIBLE_DEVICES is set.

static std::string with_prepended_pythonpath(const fs::path& dir) {
    const char separator = ':';
    const char* current = std::getenv("PYTHONPATH");
    return dir.string() + ((current && current[0] != '\0')
        ? std::string(1, separator) + current
        : "");
}

static fs::path create_omni_rocm_shim_dir() {
    fs::path runtime_base = path_from_utf8(get_runtime_dir());
    std::random_device rd;
    std::uniform_int_distribution<unsigned int> dis(0, 0xFFFFFF);

    std::error_code ec;
    for (int attempt = 0; attempt < 8; ++attempt) {
        auto nonce = static_cast<unsigned long long>(
            std::chrono::steady_clock::now().time_since_epoch().count());
        std::ostringstream suffix;
        suffix << "vllm-omni-rocm-shim-" << nonce << "-" << std::hex << dis(rd);
        fs::path candidate = runtime_base / suffix.str();
        ec.clear();
        if (fs::create_directory(candidate, ec)) {
            return candidate;
        }
    }
    throw std::runtime_error("Failed to create temporary directory for vLLM-Omni ROCm startup shim");
}

static fs::path write_omni_rocm_startup_shim() {
    fs::path dir = create_omni_rocm_shim_dir();
    fs::path file = dir / "sitecustomize.py";

    std::ofstream out(file, std::ios::trunc);
    if (!out.is_open()) {
        std::error_code ec;
        fs::remove_all(dir, ec);
        throw std::runtime_error("Unable to write vLLM-Omni ROCm startup shim: " + file.string());
    }

    out << R"PY(# Auto-generated by Lemonade for the vLLM-Omni ROCm backend.
import sys

try:
    import vllm.utils.import_utils as _vllm_import_utils

    def _disabled_import_pynvml():
        raise ModuleNotFoundError(
            "vLLM NVML probe disabled by Lemonade for the ROCm backend"
        )

    _vllm_import_utils.import_pynvml = _disabled_import_pynvml
except (ImportError, AttributeError) as exc:
    print(
        f"Lemonade warning: unable to disable vLLM NVML probe: {exc}",
        file=sys.stderr,
    )
)PY";

    if (!out.good()) {
        std::error_code ec;
        fs::remove_all(dir, ec);
        throw std::runtime_error("Failed to write vLLM-Omni ROCm startup shim: " + file.string());
    }
    return dir;
}

static void cleanup_omni_rocm_shim_dir(fs::path& shim_dir) {
    if (shim_dir.empty()) {
        return;
    }
    std::error_code ec;
    fs::remove_all(shim_dir, ec);
    if (ec) {
        LOG(WARNING, "vLLM-Omni") << "Failed to remove ROCm startup shim directory: "
                                  << shim_dir << " (" << ec.message() << ")" << std::endl;
    }
    shim_dir.clear();
}

static void configure_omni_rocm_env(
    const std::string& backend,
    std::vector<std::pair<std::string, std::string>>& env_vars,
    fs::path& shim_dir) {
    if (backend != "rocm") {
        return;
    }
    cleanup_omni_rocm_shim_dir(shim_dir);
    shim_dir = write_omni_rocm_startup_shim();
    env_vars.push_back({"PYTHONPATH", with_prepended_pythonpath(shim_dir)});
}

// ----------------------------------------------------------------------------

InstallParams VLLMOmniServer::get_install_params(const std::string& backend, const std::string& version) {
    InstallParams params;

    if (backend == "rocm") {
        params.repo = "lemonade-sdk/vllm-rocm";
        std::string target_arch =
            SystemInfo::rocm_asset_family(SystemInfo::get_rocm_arch());
        if (target_arch.empty()) {
            throw std::runtime_error(
                SystemInfo::get_unsupported_backend_error("vllm-omni", "rocm")
            );
        }
#ifdef __linux__
        // One release per GPU target: release tag is {version}-{target_arch},
        // e.g. vllm-omni0.23.0rc1-rocm7.14.0-gfx1151. The version pin in
        // backend_versions.json already carries the vllm-omni prefix.
        std::string release_tag = version + "-" + target_arch;
        params.version_override = release_tag;
        params.filename = release_tag + "-x64.tar.gz";
#else
        throw std::runtime_error("vLLM-Omni ROCm is only supported on Linux");
#endif
    } else {
        throw std::runtime_error("vLLM-Omni backend '" + backend + "' is not supported. Supported: rocm");
    }

    return params;
}

VLLMOmniServer::VLLMOmniServer(const std::string& log_level, ModelManager* model_manager, BackendManager* backend_manager)
    : WrappedServer("vllm-omni-server", log_level, model_manager, backend_manager) {
}

VLLMOmniServer::~VLLMOmniServer() {
    unload();
}

void VLLMOmniServer::load(const std::string& model_name,
                          const ModelInfo& model_info,
                          const RecipeOptions& options,
                          bool do_not_upgrade) {
    LOG(INFO, "vLLM-Omni") << "Loading model: " << model_name << std::endl;

    std::string omni_backend = options.get_option("vllm-omni_backend");
    std::string omni_args = options.get_option("vllm_omni_args");
    int ctx_size = options.get_option("ctx_size");
    max_model_len_ = ctx_size;

    RuntimeConfig::validate_backend_choice("vllm-omni", omni_backend);

    backend_manager_->install_backend(vllm_omni::spec()->recipe, omni_backend);

    // vLLM-Omni uses HuggingFace model IDs, not local file paths.
    std::string model_id = model_info.checkpoint();
    if (model_id.empty()) {
        throw std::runtime_error("Model checkpoint (HuggingFace ID) not found for: " + model_name);
    }

    // Resolve the single-GPU deploy config. Per-model override via the
    // `deploy_config` key in server_models.json; falls back to the Qwen2.5-Omni
    // config. The upstream deploy defaults target multi-GPU hosts and put a
    // stage on cuda:1, which is fatal on a single-GPU box — so a colocating
    // deploy config is required.
    std::string deploy_rel = model_info.extra<std::string>(
        "deploy_config", "resources/omni_deploy/qwen2_5_omni_1gpu.yaml");
    std::string deploy_path = utils::get_resource_path(deploy_rel);
    if (!fs::exists(path_from_utf8(deploy_path))) {
        throw std::runtime_error("vLLM-Omni deploy config not found: " + deploy_path);
    }

    port_ = choose_port();

    std::string executable = BackendUtils::get_backend_binary_path(*vllm_omni::spec(), omni_backend);

    std::vector<std::string> args;
    args.push_back("serve");
    args.push_back(model_id);
    args.push_back("--omni");
    args.push_back("--deploy-config");
    args.push_back(deploy_path);
    args.push_back("--host");
    args.push_back("127.0.0.1");
    args.push_back("--port");
    args.push_back(std::to_string(port_));
    // Serve using the Lemonade model name so forwarded requests match.
    args.push_back("--served-model-name");
    args.push_back(model_name);
    args.push_back("--max-model-len");
    args.push_back(std::to_string(ctx_size));

    if (!omni_args.empty()) {
        // Reject user overrides of the launch args Lemonade manages: overriding
        // e.g. --port would start the backend where Lemonade isn't polling, and
        // --deploy-config would bypass the required single-GPU configuration.
        static const std::set<std::string> reserved_flags = {
            "--host", "--port", "--served-model-name", "--max-model-len",
            "--deploy-config"};
        std::string validation_error = validate_custom_args(omni_args, reserved_flags);
        if (!validation_error.empty()) {
            throw std::invalid_argument(
                "Invalid custom vllm-omni-server arguments:\n" + validation_error);
        }

        LOG(DEBUG, "vLLM-Omni") << "Adding user arguments: " << omni_args << std::endl;
        // Quote-aware parsing (shared with the other backends) so values like
        // --some-option "value with spaces" survive as a single argument.
        for (const auto& tok : parse_custom_args(omni_args)) {
            args.push_back(tok);
        }
    }

    LOG(INFO, "vLLM-Omni") << "Starting vllm-omni-server on port " << port_ << "..." << std::endl;

    std::vector<std::pair<std::string, std::string>> env_vars;
    configure_omni_rocm_env(omni_backend, env_vars, rocm_shim_dir_);
    // Enable ROCm flash attention (the launcher script handles LD_LIBRARY_PATH).
    env_vars.push_back({"FLASH_ATTENTION_TRITON_AMD_ENABLE", "TRUE"});
    // Prevent system/user Python packages from leaking into the bundled env.
    env_vars.push_back({"PYTHONNOUSERSITE", "1"});

    bool inherit_output = (log_level_ == "info") || is_debug();
    set_process_handle(ProcessManager::start_process(executable, args, "", inherit_output, true, env_vars));

    // Omni serves /v1/models once all stages register; it has no reliable
    // /health. Multi-stage boot + JIT can take minutes on cold start.
    if (!wait_for_ready("/v1/models", VLLM_OMNI_READY_TIMEOUT_SECONDS)) {
        const ProcessHandle handle = consume_process_handle_for_cleanup();
        if (has_process_handle(handle)) {
            ProcessManager::stop_process(handle);
        }
        cleanup_omni_rocm_shim_dir(rocm_shim_dir_);
        max_model_len_ = 0;
        std::string err = "vllm-omni-server failed to start within timeout";
        if (needs_gfx1151_cwsr_fix()) {
            err += ". Your kernel may be missing the gfx1151 CWSR fix — "
                   "see https://lemonade-server.ai/gfx1151_linux.html";
        }
        throw std::runtime_error(err);
    }

    LOG(DEBUG, "vLLM-Omni") << "Model loaded on port " << port_ << std::endl;
}

void VLLMOmniServer::unload() {
    stop_backend_watchdog();
    LOG(INFO, "vLLM-Omni") << "Unloading model..." << std::endl;

    const ProcessHandle handle = consume_process_handle_for_cleanup();
    if (has_process_handle(handle)) {
        ProcessManager::stop_process(handle);
    }
    cleanup_omni_rocm_shim_dir(rocm_shim_dir_);
    max_model_len_ = 0;
}

// Apply the max_completion_tokens -> max_tokens compatibility alias (as the
// plain vLLM backend does) so OpenAI-style clients work regardless of which key
// vllm-omni-server honors. Shared by the streaming and non-streaming paths.
json VLLMOmniServer::prepare_request(const json& request) {
    return JsonUtils::with_legacy_max_tokens_alias(request);
}

json VLLMOmniServer::chat_completion(const json& request) {
    return forward_request("/v1/chat/completions", prepare_request(request));
}

json VLLMOmniServer::completion(const json& request) {
    return forward_request("/v1/completions", prepare_request(request));
}

json VLLMOmniServer::responses(const json& request) {
    return forward_request("/v1/responses", request);
}

void VLLMOmniServer::forward_streaming_request(const std::string& endpoint,
                                               const std::string& request_body,
                                               httplib::DataSink& sink,
                                               bool sse,
                                               long timeout_seconds,
                                               TelemetryCallback telemetry_callback) {
    std::string body = request_body;
    if (endpoint == "/v1/chat/completions" || endpoint == "/v1/completions") {
        try {
            body = prepare_request(json::parse(request_body)).dump();
        } catch (...) {
            // Forward the original request if it cannot be parsed.
        }
    }
    WrappedServer::forward_streaming_request(endpoint, body, sink, sse,
                                             timeout_seconds, telemetry_callback);
}

}  // namespace backends
}  // namespace lemon

namespace lemon {
namespace backends {
namespace vllm_omni {

std::unique_ptr<WrappedServer> create(const BackendContext& ctx) {
    return make_server<VLLMOmniServer>(ctx);
}

const BackendSpec* spec() { return make_spec<VLLMOmniServer>(descriptor, /*split=*/true); }
const BackendOps* ops() { return default_backend_ops(); }

}  // namespace vllm_omni
}  // namespace backends
}  // namespace lemon
