name: 'Cleanup Processes (Linux)'
description: 'Kill all lemonade, Python, llama-server, and conda processes on Linux'
runs:
  using: "composite"
  steps:
    - name: Kill zombie processes
      shell: bash
      run: |
        echo "========================================"
        echo "Cleaning up processes on Linux..."
        echo "========================================"
        
        # Kill processes aggressively by pattern
        kill_by_pattern() {
            local pattern=$1
            local description=$2
            
            echo ""
            echo "Killing $description processes..."
            
            # Find and kill in one shot with SIGKILL
            pkill -9 -f "$pattern" 2>/dev/null && echo "  Killed processes matching: $pattern" || echo "  No $description processes found"
        }
        
        # Kill by exact name (even more aggressive)
        kill_by_exact_name() {
            local name=$1
            
            if pgrep -x "$name" > /dev/null 2>&1; then
                echo "Killing $name (exact match)..."
                pkill -9 -x "$name"
                sleep 0.5
                # Verify it's dead
                if pgrep -x "$name" > /dev/null 2>&1; then
                    echo "  WARNING: $name still running after kill!"
                else
                    echo "  Successfully killed $name"
                fi
            fi
        }
        
        # Kill everything lemonade-related
        kill_by_pattern "lemonade" "lemonade"
        
        # Kill Python processes (this is aggressive - be careful!)
        kill_by_pattern "python" "Python"
        
        # Kill llama processes
        kill_by_pattern "llama-server" "llama-server"
        kill_by_pattern "llama-cli" "llama-cli"
        kill_by_pattern "llama-bench" "llama-bench"
        
        # Kill conda processes
        kill_by_pattern "conda" "conda"
        
        # Additional pass: kill by exact process names
        echo ""
        echo "Second pass: killing by exact name..."
        for proc_name in lemonade-server lemonade-router lemonade-server-beta lemonade-server-dev lemonade-tray llama-server llama-cli llama-bench; do
            kill_by_exact_name "$proc_name"
        done
        
        # Wait for processes to die
        sleep 2
        
        # FINAL VERIFICATION - show what's still alive
        echo ""
        echo "=== Verification: checking for remaining processes ==="
        if pgrep -f "lemonade|llama|conda" > /dev/null 2>&1; then
            echo "WARNING: Some processes still alive:"
            ps aux | grep -E "lemonade|llama|conda" | grep -v grep | grep -v "cleanup-processes" || true
            
            # NUCLEAR OPTION: Kill them with extreme prejudice
            echo "Using nuclear option..."
            pkill -9 -f "lemonade" 2>/dev/null || true
            pkill -9 -f "llama" 2>/dev/null || true
            pkill -9 -f "conda" 2>/dev/null || true
            sleep 1
            
            # Check again
            if pgrep -f "lemonade|llama|conda" > /dev/null 2>&1; then
                echo "ERROR: Processes STILL alive after nuclear option!"
                ps aux | grep -E "lemonade|llama|conda" | grep -v grep || true
                
                # Check if processes are in D-state (uninterruptible sleep)
                echo ""
                echo "Checking for D-state processes (GPU driver issue)..."
                D_STATE_FOUND=false
                for pid in $(pgrep -f "lemonade|llama|conda" 2>/dev/null); do
                    state=$(ps -o state= -p $pid 2>/dev/null | tr -d ' ')
                    if [ "$state" = "D" ]; then
                        echo "  Process $pid is in D-state (uninterruptible sleep)"
                        # Show what it's waiting on
                        wchan=$(cat /proc/$pid/wchan 2>/dev/null || echo "unknown")
                        echo "    Waiting on: $wchan"
                        D_STATE_FOUND=true
                    fi
                done
                
                # If D-state processes found, try GPU driver restart
                if [ "$D_STATE_FOUND" = "true" ]; then
                    echo ""
                    echo "D-state processes detected - attempting GPU driver restart..."
                    
                    # Check if amdgpu module is loaded
                    if lsmod | grep -q "amdgpu"; then
                        echo "AMD GPU driver detected, attempting restart..."
                        
                        # Try to unload and reload amdgpu module
                        # Capture stderr to show actual error message
                        UNLOAD_ERROR=$(sudo -n modprobe -r amdgpu 2>&1)
                        if [ $? -eq 0 ]; then
                            echo "  Unloaded amdgpu module"
                            sleep 2
                            
                            RELOAD_ERROR=$(sudo -n modprobe amdgpu 2>&1)
                            if [ $? -eq 0 ]; then
                                echo "  Reloaded amdgpu module"
                                sleep 2
                                
                                # Check if processes are now gone
                                if pgrep -f "lemonade|llama|conda" > /dev/null 2>&1; then
                                    echo "  WARNING: Processes still alive after driver restart"
                                else
                                    echo "  SUCCESS: Driver restart cleared stuck processes"
                                fi
                            else
                                echo "  ERROR: Failed to reload amdgpu module"
                                echo "  Reason: $RELOAD_ERROR"
                            fi
                        else
                            echo "  WARNING: Unable to restart GPU driver"
                            echo "  Reason: $UNLOAD_ERROR"
                            echo "  This may require a system reboot to clear D-state processes"
                        fi
                    else
                        echo "  No AMD GPU driver loaded, or different GPU vendor"
                        echo "  D-state processes may require system reboot"
                    fi
                else
                    echo "No D-state processes found - processes may be stuck for other reasons"
                fi
            else
                echo "Nuclear option successful"
            fi
        else
            echo "All target processes terminated successfully"
        fi
        
        # Clean up lock files and PID files
        echo ""
        echo "Cleaning up lock and PID files..."
        rm -f /tmp/lemonade*.lock 2>/dev/null || true
        rm -f /tmp/lemonade*.pid 2>/dev/null || true
        rm -f /tmp/lemonade-router.pid 2>/dev/null || true
        echo "Lock and PID files cleaned."
        
        # Clean up log files
        echo ""
        echo "Cleaning up log files..."
        rm -f /tmp/lemonade*.log 2>/dev/null || true
        rm -f /tmp/lemonade-server*.log 2>/dev/null || true
        rm -f /tmp/lemonade-router*.log 2>/dev/null || true
        echo "Log files cleaned."
        
        # Clean up installation directories
        echo ""
        echo "Cleaning up lemonade installation directories..."
        if [ -d "$HOME/.local/share/lemonade-server" ]; then
            rm -rf "$HOME/.local/share/lemonade-server" 2>/dev/null || true
            echo "Removed: $HOME/.local/share/lemonade-server"
        else
            echo "No lemonade-server directory found in ~/.local/share/"
        fi
        
        echo ""
        echo "========================================"
        echo "Process cleanup complete!"
        echo "========================================"
        
        # Verification: Check if any processes are still running
        echo ""
        echo "Verifying cleanup..."
        STILL_RUNNING=0
        
        # Check for lemonade processes
        remaining=$(ps aux | grep -E "lemonade" | grep -v grep | grep -v "cleanup-processes" || true)
        if [ -n "$remaining" ]; then
            echo "  WARNING: Found lemonade process(es) still running:" >&2
            echo "$remaining" | awk '{print "    - PID " $2 ": " $11}' >&2
            STILL_RUNNING=$((STILL_RUNNING + 1))
        fi
        
        # Check for test-related Python processes (exclude system python and runner)
        remaining=$(ps aux | grep -E "pytest|unittest|test.*\.py|lemonade.*\.py" | grep -v grep | grep -v "cleanup-processes" || true)
        if [ -n "$remaining" ]; then
            echo "  WARNING: Found test Python process(es) still running:" >&2
            echo "$remaining" | awk '{print "    - PID " $2 ": " $11}' >&2
            STILL_RUNNING=$((STILL_RUNNING + 1))
        fi
        
        # Check for llama-server and ryzenai-serve
        for pattern in "llama-server" "ryzenai-serve" "flm"; do
            remaining=$(ps aux | grep -E "$pattern" | grep -v grep | grep -v "cleanup-processes" || true)
            if [ -n "$remaining" ]; then
                echo "  WARNING: Found $pattern process(es) still running:" >&2
                echo "$remaining" | awk '{print "    - PID " $2 ": " $11}' >&2
                STILL_RUNNING=$((STILL_RUNNING + 1))
            fi
        done
        
        if [ $STILL_RUNNING -eq 0 ]; then
            echo "  [OK] All target processes successfully terminated"
        else
            echo ""
            echo "  [ERROR] Some processes still running after cleanup!" >&2
            echo "  This may cause test failures or conflicts." >&2
            exit 1
        fi