name: Report lemonade-sdk install size

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  install-report:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            scenario: plain
            python: '3.x'
          - os: ubuntu-latest
            scenario: llama-vulkan
            python: '3.x'
          - os: ubuntu-latest
            scenario: llama-rocm
            python: '3.x'
          - os: ubuntu-latest
            scenario: oga-cpu
            python: '3.x'
          - os: windows-latest
            scenario: plain
            python: '3.x'
          - os: windows-latest
            scenario: llama-vulkan
            python: '3.x'
          - os: windows-latest
            scenario: llama-rocm
            python: '3.x'
          - os: windows-latest
            scenario: oga-cpu
            python: '3.x'
          - os: windows-latest
            scenario: oga-ryzenai
            python: '3.10'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Measure installation stats
        shell: bash
        run: |
          set -euo pipefail
          python -m venv venv
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            source venv/Scripts/activate
          else
            source venv/bin/activate
          fi
          python -m pip install --upgrade pip tabulate
          START=$(date +%s)
          case "${{ matrix.scenario }}" in
            plain)
              python -m pip install lemonade-sdk
              ;;
            llama-vulkan)
              python -m pip install lemonade-sdk
              lemonade-install --llamacpp vulkan
              ;;
            llama-rocm)
              python -m pip install lemonade-sdk
              PYTHONPATH=src LEMONADE_CI_MODE=1 LEMONADE_ROCM_OVERRIDE=gfx1151 \
                python -m lemonade_install.install --llamacpp rocm
              ;;
            oga-cpu)
              python -m pip install 'lemonade-sdk[oga-cpu]'
              ;;
            oga-ryzenai)
              python -m pip install -e .
              python -m pip install -e .[oga-ryzenai] --extra-index-url https://pypi.amd.com/simple
              ;;
          esac
          END=$(date +%s)
          INSTALL_TIME=$((END-START))
          echo "Total install time: ${INSTALL_TIME} seconds" | tee -a "$GITHUB_STEP_SUMMARY"
          python .github/workflows/install_report.py --stats stats.json --install-time "$INSTALL_TIME" | tee -a "$GITHUB_STEP_SUMMARY"
      - name: Upload stats
        uses: actions/upload-artifact@v4
        with:
          name: stats-${{ matrix.os }}-${{ matrix.scenario }}
          path: stats.json

  summary:
    needs: install-report
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p artifacts
      - uses: actions/download-artifact@v4
        if: ${{ always() }}
        with:
          path: artifacts
        continue-on-error: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: python -m pip install tabulate
      - name: Generate summary
        run: |
          echo '## Installation Summary' | tee -a "$GITHUB_STEP_SUMMARY"
          python .github/workflows/aggregate_stats.py | tee -a "$GITHUB_STEP_SUMMARY"
