find_program(NEXUS_CARGO_EXECUTABLE cargo REQUIRED)
option(NEXUS_CARGO_OFFLINE "Build Rust transport using locally packaged crates" OFF)
set(_cargo_flags --locked)
if(NEXUS_CARGO_OFFLINE)
    list(APPEND _cargo_flags --offline)
endif()
set(_rust_environment)
if(MSVC AND NOT CMAKE_MSVC_RUNTIME_LIBRARY MATCHES "DLL")
    list(APPEND _rust_environment "RUSTFLAGS=-Ctarget-feature=+crt-static")
endif()
if(APPLE AND CMAKE_OSX_DEPLOYMENT_TARGET)
    list(APPEND _rust_environment "MACOSX_DEPLOYMENT_TARGET=${CMAKE_OSX_DEPLOYMENT_TARGET}")
endif()
foreach(_transport boringtun-ffi virtual-netstack)
    string(REPLACE "-" "_" _crate "lemonade-${_transport}")
    set(_manifest "${CMAKE_CURRENT_SOURCE_DIR}/crates/${_transport}/Cargo.toml")
    set(_target_dir "${CMAKE_CURRENT_BINARY_DIR}/cargo/${_transport}")
    if(APPLE AND CMAKE_OSX_DEPLOYMENT_TARGET)
        string(APPEND _target_dir "-${CMAKE_OSX_DEPLOYMENT_TARGET}")
    endif()
    if(WIN32)
        set(_archive "${_target_dir}/release/${_crate}.lib")
    else()
        set(_archive "${_target_dir}/release/lib${_crate}.a")
    endif()
    file(GLOB_RECURSE _rust_sources CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/crates/${_transport}/src/*.rs")
    add_custom_command(OUTPUT "${_archive}"
        COMMAND ${CMAKE_COMMAND} -E env ${_rust_environment} ${NEXUS_CARGO_EXECUTABLE}
            build --release ${_cargo_flags} --manifest-path "${_manifest}" --target-dir "${_target_dir}"
        DEPENDS ${_rust_sources} "${_manifest}" "${CMAKE_CURRENT_SOURCE_DIR}/crates/${_transport}/Cargo.lock"
        WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/crates/${_transport}"
        VERBATIM)
    add_custom_target(${_transport}-build DEPENDS "${_archive}")
    add_library(${_transport} STATIC IMPORTED GLOBAL)
    set_target_properties(${_transport} PROPERTIES IMPORTED_LOCATION "${_archive}"
        INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_SOURCE_DIR}/crates/${_transport}/include")
    add_dependencies(${_transport} ${_transport}-build)
    if(APPLE)
        target_link_libraries(${_transport} INTERFACE "-framework Security" "-framework SystemConfiguration")
    elseif(WIN32)
        target_link_libraries(${_transport} INTERFACE ws2_32 userenv bcrypt ntdll)
    else()
        target_link_libraries(${_transport} INTERFACE pthread dl m)
    endif()
endforeach()
